#:sdk Microsoft.NET.Sdk.Web
#:package Microsoft.CodeAnalysis.CSharp@4.7.0
#:package MediatR@12.1.1
#:package ValueOf@3.0.0
#:property LangVersion=preview
#:property TargetFramework=net11.0
#:property Nullable=enable
#:property ImplicitUsings=enable

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

// 1. 领域事件实现
[Generator]
public class DomainEventGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new DomainEventSyntaxReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (!(context.SyntaxContextReceiver is DomainEventSyntaxReceiver receiver))
            return;

        foreach (var entity in receiver.Entities)
        {
            // 生成领域事件接口
            var eventInterface = GenerateEventInterface(entity);
            context.AddSource($"I{entity.Name}DomainEvent.g.cs", SourceText.From(eventInterface, Encoding.UTF8));

            // 生成基础领域事件
            var baseEvent = GenerateBaseDomainEvent(entity);
            context.AddSource($"{entity.Name}DomainEvent.g.cs", SourceText.From(baseEvent, Encoding.UTF8));

            // 生成具体领域事件
            var createdEvent = GenerateCreatedEvent(entity);
            context.AddSource($"{entity.Name}CreatedEvent.g.cs", SourceText.From(createdEvent, Encoding.UTF8));
        }
    }

    private string GenerateEventInterface(EntityInfo entity)
    {
        return $@"// <auto-generated/>
using MediatR;

namespace {entity.Namespace}.Domain.Events
{{
    public interface I{entity.Name}DomainEvent : INotification
    {{
        {entity.Name} Entity {{ get; }}
    }}
}}";
    }

    private string GenerateBaseDomainEvent(EntityInfo entity)
    {
        return $@"// <auto-generated/>
using MediatR;

namespace {entity.Namespace}.Domain.Events
{{
    public abstract class {entity.Name}DomainEvent : I{entity.Name}DomainEvent
    {{
        public {entity.Name} Entity {{ get; }}

        protected {entity.Name}DomainEvent({entity.Name} entity)
        {{
            Entity = entity;
        }}
    }}
}}";
    }

    private string GenerateCreatedEvent(EntityInfo entity)
    {
        return $@"// <auto-generated/>
namespace {entity.Namespace}.Domain.Events
{{
    public class {entity.Name}CreatedEvent : {entity.Name}DomainEvent
    {{
        public {entity.Name}CreatedEvent({entity.Name} entity) : base(entity)
        {{
        }}
    }}
}}";
    }
}

// 2. 值对象支持
[Generator]
public class ValueObjectGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new ValueObjectSyntaxReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (!(context.SyntaxContextReceiver is ValueObjectSyntaxReceiver receiver))
            return;

        foreach (var vo in receiver.ValueObjects)
        {
            var source = GenerateValueObject(vo);
            context.AddSource($"{vo.Name}.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    private string GenerateValueObject(ValueObjectInfo vo)
    {
        return $@"// <auto-generated/>
using ValueOf;

namespace {vo.Namespace}.Domain.ValueObjects
{{
    public class {vo.Name} : ValueOf<{vo.UnderlyingType}, {vo.Name}>
    {{
        protected override void Validate()
        {{
            if (Value == default({vo.UnderlyingType}))
                throw new ArgumentException(""Value cannot be empty"", nameof(Value));
        }}
    }}
}}";
    }
}

// 3. 微服务模板代码
[Generator]
public class MicroserviceGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new MicroserviceSyntaxReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (!(context.SyntaxContextReceiver is MicroserviceSyntaxReceiver receiver))
            return;

        foreach (var service in receiver.Services)
        {
            // 生成gRPC服务
            var grpcService = GenerateGrpcService(service);
            context.AddSource($"{service.Name}GrpcService.g.cs", SourceText.From(grpcService, Encoding.UTF8));

            // 生成Kafka消费者
            var kafkaConsumer = GenerateKafkaConsumer(service);
            context.AddSource($"{service.Name}KafkaConsumer.g.cs", SourceText.From(kafkaConsumer, Encoding.UTF8));
        }
    }

    private string GenerateGrpcService(ServiceInfo service)
    {
        return $@"// <auto-generated/>
using Grpc.Core;
using {service.Namespace}.Application.Interfaces;

namespace {service.Namespace}.Services
{{
    public class {service.Name}GrpcService : {service.Name}Service.{service.Name}ServiceBase
    {{
        private readonly I{service.Name}AppService _appService;

        public {service.Name}GrpcService(I{service.Name}AppService appService)
        {{
            _appService = appService;
        }}

        public override async Task<Get{service.Name}Response> Get{service.Name}(Get{service.Name}Request request, ServerCallContext context)
        {{
            var dto = await _appService.GetByIdAsync(request.Id);
            return new Get{service.Name}Response {{ Data = dto }};
        }}
    }}
}}";
    }

    private string GenerateKafkaConsumer(ServiceInfo service)
    {
        return $@"// <auto-generated/>
using Confluent.Kafka;
using MediatR;
using {service.Namespace}.Domain.Events;

namespace {service.Namespace}.Services
{{
    public class {service.Name}KafkaConsumer : BackgroundService
    {{
        private readonly IConsumer<Ignore, string> _consumer;
        private readonly IMediator _mediator;

        public {service.Name}KafkaConsumer(IConsumer<Ignore, string> consumer, IMediator mediator)
        {{
            _consumer = consumer;
            _mediator = mediator;
        }}

        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {{
            _consumer.Subscribe(""{service.Name}Events"");

            while (!stoppingToken.IsCancellationRequested)
            {{
                try
                {{
                    var consumeResult = _consumer.Consume(stoppingToken);
                    var @event = JsonSerializer.Deserialize<I{service.Name}DomainEvent>(consumeResult.Message.Value);
                    await _mediator.Publish(@event, stoppingToken);
                }}
                catch (Exception ex)
                {{
                    // 错误处理
                }}
            }}
        }}
    }}
}}";
    }
}

// 语法接收器
public class DomainEventSyntaxReceiver : ISyntaxContextReceiver
{
    public List<EntityInfo> Entities { get; } = new();

    public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
    {
        if (context.Node is ClassDeclarationSyntax classDecl &&
            classDecl.AttributeLists.Any(a => a.Attributes.Any(at => at.Name.ToString().Contains("AggregateRoot"))))
        {
            var model = context.SemanticModel.GetDeclaredSymbol(classDecl);
            if (model != null)
            {
                Entities.Add(new EntityInfo
                {
                    Name = model.Name,
                    Namespace = model.ContainingNamespace.ToDisplayString()
                });
            }
        }
    }
}

public class ValueObjectSyntaxReceiver : ISyntaxContextReceiver
{
    public List<ValueObjectInfo> ValueObjects { get; } = new();

    public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
    {
        if (context.Node is ClassDeclarationSyntax classDecl &&
            classDecl.AttributeLists.Any(a => a.Attributes.Any(at => at.Name.ToString().Contains("ValueObject"))))
        {
            var model = context.SemanticModel.GetDeclaredSymbol(classDecl);
            if (model != null)
            {
                ValueObjects.Add(new ValueObjectInfo
                {
                    Name = model.Name,
                    Namespace = model.ContainingNamespace.ToDisplayString(),
                    UnderlyingType = "string" // 默认类型，可从属性获取
                });
            }
        }
    }
}

public class MicroserviceSyntaxReceiver : ISyntaxContextReceiver
{
    public List<ServiceInfo> Services { get; } = new();

    public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
    {
        if (context.Node is ClassDeclarationSyntax classDecl &&
            classDecl.AttributeLists.Any(a => a.Attributes.Any(at => at.Name.ToString().Contains("Microservice"))))
        {
            var model = context.SemanticModel.GetDeclaredSymbol(classDecl);
            if (model != null)
            {
                Services.Add(new ServiceInfo
                {
                    Name = model.Name,
                    Namespace = model.ContainingNamespace.ToDisplayString()
                });
            }
        }
    }
}

// 信息类
public class EntityInfo
{
    public string Name { get; set; }
    public string Namespace { get; set; }
}

public class ValueObjectInfo
{
    public string Name { get; set; }
    public string Namespace { get; set; }
    public string UnderlyingType { get; set; }
}

public class ServiceInfo
{
    public string Name { get; set; }
    public string Namespace { get; set; }
}

private string GenerateBlazorComponent(EntityInfo entity)
{
    return $@"// <auto-generated/>
using Microsoft.AspNetCore.Components;
using {entity.Namespace}.Application.Dtos;
using {entity.Namespace}.Application.Interfaces;

namespace {entity.Namespace}.Web.Components
{{
    public partial class {entity.Name}Component : ComponentBase
    {{
        [Inject] 
        public I{entity.Name}AppService Service {{ get; set; }}

        private List<{entity.Name}Dto> items = new();
        private {entity.Name}Dto currentItem = new();
        private bool showEditDialog;

        protected override async Task OnInitializedAsync()
        {{
            items = (await Service.GetAllAsync()).ToList();
        }}

        private async Task HandleValidSubmit()
        {{
            if(currentItem.Id == 0)
                await Service.CreateAsync(currentItem);
            else
                await Service.UpdateAsync(currentItem);
            
            items = (await Service.GetAllAsync()).ToList();
            showEditDialog = false;
        }}

        private void EditItem({entity.Name}Dto item)
        {{
            currentItem = item;
            showEditDialog = true;
        }}

        private async Task DeleteItem(int id)
        {{
            await Service.DeleteAsync(id);
            items = (await Service.GetAllAsync()).ToList();
        }}
    }}
}}";
}

private string GenerateWolverineCqrsHandlers(EntityInfo entity)
{
    return $@"// <auto-generated/>
using Wolverine;
using {entity.Namespace}.Application.Commands;
using {entity.Namespace}.Domain;

namespace {entity.Namespace}.Application.Handlers
{{
    public static class {entity.Name}CommandHandlers
    {{
        [Transactional]
        public static async Task Handle(
            Create{entity.Name}Command command, 
            I{entity.Name}Repository repository,
            I{entity.Name}EventBus eventBus)
        {{
            var entity = new {entity.Name} {{ /* 初始化 */ }};
            await repository.AddAsync(entity);
            await eventBus.Publish(new {entity.Name}CreatedEvent(entity));
        }}

        // 其他命令处理器...
    }}
}}";
}

private string GenerateWolverineEventHandlers(EntityInfo entity)
{
    return $@"// <auto-generated/>
using Wolverine;
using {entity.Namespace}.Domain.Events;

namespace {entity.Namespace}.Application.EventHandlers
{{
    public static class {entity.Name}EventHandlers
    {{
        [Transactional]
        public static async Task Handle({entity.Name}CreatedEvent @event, 
            I{entity.Name}Repository repository, 
            IMessageContext context)
        {{
            await repository.AddAsync(@event.Entity);
            await context.SendAsync(new {entity.Name}CreatedNotification(@event.Entity));
        }}

        // 其他事件处理器...
    }}
}}";
}

private string GenerateWolverineEventBus(EntityInfo entity)
{
    return $@"// <auto-generated/>
using Wolverine;
using {entity.Namespace}.Domain.Events;

namespace {entity.Namespace}.Infrastructure
{{
    public class {entity.Name}EventBus : I{entity.Name}EventBus
    {{
        private readonly IMessageBus _bus;

        public {entity.Name}EventBus(IMessageBus bus)
        {{
            _bus = bus;
        }}

        public async Task Publish<TEvent>(TEvent @event) where TEvent : I{entity.Name}DomainEvent
        {{
            await _bus.PublishAsync(@event);
        }}
    }}
}}";
}

private string GenerateMapperlyMapping(EntityInfo entity)
    {
        return $@"// <auto-generated/>
using Mapster;
using {entity.Namespace}.Domain.Entities;
using {entity.Namespace}.Application.Dtos;

namespace {entity.Namespace}.Application.Mappings
{{
    [Mapper]
    public partial class {entity.Name}Mapper
    {{
        public partial {entity.Name}Dto ToDto({entity.Name} entity);
        public partial {entity.Name} FromCreateDto({entity.Name}CreateDto dto);
        public partial {entity.Name} FromUpdateDto({entity.Name}UpdateDto dto);
    }}
}}";
    }
    
    private string GenerateVueComponent(EntityInfo entity)
    {
        return $@"// <auto-generated/>
using System.Text.Json;
using {entity.Namespace}.Application.Dtos;

namespace {entity.Namespace}.Web.VueComponents
{{
    public class {entity.Name}Component
    {{
        private readonly HttpClient _httpClient;
        private const string BaseUrl = ""api/{entity.Name.ToLower()}"";

        public {entity.Name}Component(HttpClient httpClient)
        {{
            _httpClient = httpClient;
        }}

        public async Task<List<{entity.Name}Dto>> GetAllAsync()
        {{
            var response = await _httpClient.GetAsync(BaseUrl);
            return await response.Content.ReadFromJsonAsync<List<{entity.Name}Dto>>();
        }}

        public async Task<{entity.Name}Dto> GetByIdAsync(int id)
        {{
            var response = await _httpClient.GetAsync($""{{BaseUrl}}/{{id}}"");
            return await response.Content.ReadFromJsonAsync<{entity.Name}Dto>();
        }}

        public async Task CreateAsync({entity.Name}Dto dto)
        {{
            var content = new StringContent(JsonSerializer.Serialize(dto), Encoding.UTF8, ""application/json"");
            await _httpClient.PostAsync(BaseUrl, content);
        }}

        public async Task UpdateAsync({entity.Name}Dto dto)
        {{
            var content = new StringContent(JsonSerializer.Serialize(dto), Encoding.UTF8, ""application/json"");
            await _httpClient.PutAsync($""{{BaseUrl}}/{{dto.Id}}"", content);
        }}

        public async Task DeleteAsync(int id)
        {{
            await _httpClient.DeleteAsync($""{{BaseUrl}}/{{id}}"");
        }}
    }}
}}";
    }
}

private string GenerateAxiosProxy(EntityInfo entity)
{
    return $@"// <auto-generated/>
using System.Text.Json;
using {entity.Namespace}.Application.Dtos;

namespace {entity.Namespace}.Web.Proxies
{{
    public class {entity.Name}AxiosProxy
    {{
        private readonly HttpClient _httpClient;
        private const string BaseUrl = ""api/{entity.Name.ToLower()}"";

        public {entity.Name}AxiosProxy(HttpClient httpClient)
        {{
            _httpClient = httpClient;
        }}

        public async Task<List<{entity.Name}Dto>> GetAllAsync()
        {{
            var response = await _httpClient.GetAsync(BaseUrl);
            return await response.Content.ReadFromJsonAsync<List<{entity.Name}Dto>>();
        }}

        public async Task<{entity.Name}Dto> GetByIdAsync(int id)
        {{
            var response = await _httpClient.GetAsync($""{{BaseUrl}}/{{id}}"");
            return await response.Content.ReadFromJsonAsync<{entity.Name}Dto>();
        }}

        public async Task CreateAsync({entity.Name}Dto dto)
        {{
            var content = new StringContent(JsonSerializer.Serialize(dto), Encoding.UTF8, ""application/json"");
            await _httpClient.PostAsync(BaseUrl, content);
        }}

        public async Task UpdateAsync({entity.Name}Dto dto)
        {{
            var content = new StringContent(JsonSerializer.Serialize(dto), Encoding.UTF8, ""application/json"");
            await _httpClient.PutAsync($""{{BaseUrl}}/{{dto.Id}}"", content);
        }}

        public async Task DeleteAsync(int id)
        {{
            await _httpClient.DeleteAsync($""{{BaseUrl}}/{{id}}"");
        }}
    }}
}}";
}

private string GenerateMapperlyMapping(EntityInfo entity)
{
    return $@"// <auto-generated/>
using Mapster;
using {entity.Namespace}.Domain.Entities;
using {entity.Namespace}.Application.Dtos;

namespace {entity.Namespace}.Application.Mappings
{{
    [Mapper]
    public partial class {entity.Name}Mapper
    {{
        public partial {entity.Name}Dto ToDto({entity.Name} entity);
        public partial {entity.Name} FromCreateDto({entity.Name}CreateDto dto);
        public partial {entity.Name} FromUpdateDto({entity.Name}UpdateDto dto);
    }}
}}";
}

private string GenerateWolverineSaga(EntityInfo entity)
{
    return $@"// <auto-generated/>
using Wolverine;
using {entity.Namespace}.Domain.Events;

namespace {entity.Namespace}.Application.Sagas
{{
    public class {entity.Name}CreationSaga : Saga
    {{
        public Guid SagaId {{ get; set; }}
        public int {entity.Name}Id {{ get; set; }}

        [Start]
        public void Start({entity.Name}CreatedEvent created)
        {{
            SagaId = Guid.NewGuid();
            {entity.Name}Id = created.Entity.Id;
        }}

        public void Handle({entity.Name}VerifiedEvent verified)
        {{
            // 处理验证完成事件
            MarkCompleted();
        }}

        public void Timeout({entity.Name}CreationTimeout timeout)
        {{
            // 处理超时
            MarkCompleted();
        }}
    }}
}}";
}

private string GenerateWebApiClient(EntityInfo entity)
{
    return $@"// <auto-generated/>
using WebApiClientCore;
using WebApiClientCore.Attributes;
using {entity.Namespace}.Application.Dtos;

namespace {entity.Namespace}.Web.Clients
{{
    [HttpHost(""http://api.example.com"")]
    public interface I{entity.Name}ApiClient : IHttpApi
    {{
        [HttpGet(""api/{entity.Name.ToLower()}"")]
        ITask<List<{entity.Name}Dto>> GetAllAsync();

        [HttpGet(""api/{entity.Name.ToLower()}/{{id}}"")]
        ITask<{entity.Name}Dto> GetByIdAsync(int id);

        [HttpPost(""api/{entity.Name.ToLower()}"")]
        ITask<int> CreateAsync([JsonContent] {entity.Name}Dto dto);

        [HttpPut(""api/{entity.Name.ToLower()}/{{id}}"")]
        ITask UpdateAsync(int id, [JsonContent] {entity.Name}Dto dto);

        [HttpDelete(""api/{entity.Name.ToLower()}/{{id}}"")]
        ITask DeleteAsync(int id);
    }}
}}";
}

private string GenerateViewModel(EntityInfo entity)
{
    return $@"// <auto-generated/>
using System.ComponentModel.DataAnnotations;
using {entity.Namespace}.Application.Dtos;

namespace {entity.Namespace}.Web.ViewModels
{{
    public class {entity.Name}ViewModel
    {{
        public int Id {{ get; set; }}

        [Required]
        [StringLength(100)]
        public string Name {{ get; set; }}

        [EmailAddress]
        public string Email {{ get; set; }}

        public static implicit operator {entity.Name}Dto({entity.Name}ViewModel vm)
        {{
            return new {entity.Name}Dto
            {{
                Id = vm.Id,
                Name = vm.Name,
                Email = vm.Email
            }};
        }}

        public static implicit operator {entity.Name}ViewModel({entity.Name}Dto dto)
        {{
            return new {entity.Name}ViewModel
            {{
                Id = dto.Id,
                Name = dto.Name,
                Email = dto.Email
            }};
        }}
    }}
}}";
}

private string GeneratePermissionService(EntityInfo entity)
{
    return $@"// <auto-generated/>
using System.Security.Claims;
using {entity.Namespace}.Domain.Entities;

namespace {entity.Namespace}.Domain.Services
{{
    public interface I{entity.Name}PermissionService
    {{
        bool CanCreate(ClaimsPrincipal user);
        bool CanRead(ClaimsPrincipal user, {entity.Name} entity);
        bool CanUpdate(ClaimsPrincipal user, {entity.Name} entity);
        bool CanDelete(ClaimsPrincipal user, {entity.Name} entity);
    }}

    public class {entity.Name}PermissionService : I{entity.Name}PermissionService
    {{
        public bool CanCreate(ClaimsPrincipal user)
        {{
            return user.IsInRole(""Admin"") || user.IsInRole(""Editor"");
        }}

        public bool CanRead(ClaimsPrincipal user, {entity.Name} entity)
        {{
            return true; // 所有人都可以读
        }}

        public bool CanUpdate(ClaimsPrincipal user, {entity.Name} entity)
        {{
            return user.IsInRole(""Admin"") || 
                  (user.IsInRole(""Editor"") && user.Identity?.Name == entity.CreatedBy);
        }}

        public bool CanDelete(ClaimsPrincipal user, {entity.Name} entity)
        {{
            return user.IsInRole(""Admin"");
        }}
    }}
}}";
}

private string GenerateMenuPermission(EntityInfo entity)
{
    return $@"// <auto-generated/>
using System.Security.Claims;

namespace {entity.Namespace}.Domain.Services
{{
    public interface I{entity.Name}MenuService
    {{
        bool CanAccessMenu(ClaimsPrincipal user);
        bool CanSeeButton(ClaimsPrincipal user, string buttonName);
    }}

    public class {entity.Name}MenuService : I{entity.Name}MenuService
    {{
        public bool CanAccessMenu(ClaimsPrincipal user)
        {{
            return user.IsInRole(""Admin"") || 
                  user.IsInRole(""Editor"") || 
                  user.IsInRole(""Viewer"");
        }}

        public bool CanSeeButton(ClaimsPrincipal user, string buttonName)
        {{
            return buttonName switch
            {{
                ""Create"" => user.IsInRole(""Admin"") || user.IsInRole(""Editor""),
                ""Edit"" => user.IsInRole(""Admin"") || user.IsInRole(""Editor""),
                ""Delete"" => user.IsInRole(""Admin""),
                _ => true
            }};
        }}
    }}
}}";
}

private string GenerateAbacPolicy(EntityInfo entity)
{
    return $@"// <auto-generated/>
using System.Security.Claims;
using {entity.Namespace}.Domain.Entities;

namespace {entity.Namespace}.Domain.Policies
{{
    public interface I{entity.Name}AbacPolicy
    {{
        bool CanAccess(ClaimsPrincipal user, {entity.Name} resource, string action);
    }}

    public class {entity.Name}AbacPolicy : I{entity.Name}AbacPolicy
    {{
        public bool CanAccess(ClaimsPrincipal user, {entity.Name} resource, string action)
        {{
            var department = user.FindFirstValue(""Department"");
            var isOwner = resource.CreatedBy == user.Identity?.Name;

            return action switch
            {{
                ""read"" => department == resource.Department || isOwner,
                ""update"" => (department == resource.Department && user.IsInRole(""Manager"")) || isOwner,
                ""delete"" => user.IsInRole(""Admin"") || (isOwner && resource.Status == ""Draft""),
                _ => false
            }};
        }}
    }}
}}";
}

private string GenerateFluentValidator(EntityInfo entity)
{
    return $@"// <auto-generated/>
using FluentValidation;
using {entity.Namespace}.Application.Dtos;

namespace {entity.Namespace}.Application.Validators
{{
    public class {entity.Name}DtoValidator : AbstractValidator<{entity.Name}Dto>
    {{
        public {entity.Name}DtoValidator()
        {{
            RuleFor(x => x.Name)
                .NotEmpty().WithMessage(""名称不能为空"")
                .MaximumLength(100).WithMessage(""名称长度不能超过100个字符"");

            RuleFor(x => x.Email)
                .EmailAddress().WithMessage(""邮箱格式不正确"")
                .When(x => !string.IsNullOrEmpty(x.Email));

            RuleFor(x => x.Age)
                .GreaterThan(0).WithMessage(""年龄必须大于0"")
                .When(x => x.Age.HasValue);
        }}
    }}
}}";
}

private string GenerateCqrsHandlers(EntityInfo entity)
{
    return $@"// <auto-generated/>
using MediatR;
using {entity.Namespace}.Domain.Entities;
using {entity.Namespace}.Domain.Interfaces;

namespace {entity.Namespace}.Application.Commands
{{
    // 查询
    public class Get{entity.Name}ByIdQuery : IRequest<{entity.Name}>
    {{
        public int Id {{ get; set; }}
    }}

    public class Get{entity.Name}ByIdHandler : IRequestHandler<Get{entity.Name}ByIdQuery, {entity.Name}>
    {{
        private readonly I{entity.Name}Repository _repository;

        public Get{entity.Name}ByIdHandler(I{entity.Name}Repository repository)
        {{
            _repository = repository;
        }}

        public async Task<{entity.Name}> Handle(Get{entity.Name}ByIdQuery request, CancellationToken cancellationToken)
        {{
            return await _repository.GetByIdAsync(request.Id);
        }}
    }}

    // 命令
    public class Create{entity.Name}Command : IRequest<int>
    {{
        public string Name {{ get; set; }}
        public string Email {{ get; set; }}
    }}

    public class Create{entity.Name}Handler : IRequestHandler<Create{entity.Name}Command, int>
    {{
        private readonly I{entity.Name}Repository _repository;
        private readonly I{entity.Name}UnitOfWork _unitOfWork;

        public Create{entity.Name}Handler(I{entity.Name}Repository repository, I{entity.Name}UnitOfWork unitOfWork)
        {{
            _repository = repository;
            _unitOfWork = unitOfWork;
        }}

        public async Task<int> Handle(Create{entity.Name}Command request, CancellationToken cancellationToken)
        {{
            var entity = new {entity.Name} {{ Name = request.Name, Email = request.Email }};
            await _repository.AddAsync(entity);
            await _unitOfWork.CommitAsync();
            return entity.Id;
        }}
    }}
}}";
}

private string GenerateReadWriteRepository(EntityInfo entity)
{
    return $@"// <auto-generated/>
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using {entity.Namespace}.Domain.Entities;

namespace {entity.Namespace}.Infrastructure.Repositories
{{
    public class {entity.Name}ReadRepository : I{entity.Name}ReadRepository
    {{
        private readonly ReadOnlyDbContext _context;

        public {entity.Name}ReadRepository(ReadOnlyDbContext context)
        {{
            _context = context;
        }}

        public async Task<{entity.Name}> GetByIdAsync(int id)
        {{
            return await _context.Set<{entity.Name}>().AsNoTracking().FirstOrDefaultAsync(x => x.Id == id);
        }}

        public async Task<IEnumerable<{entity.Name}>> GetAllAsync()
        {{
            return await _context.Set<{entity.Name}>().AsNoTracking().ToListAsync();
        }}
    }}

    public class {entity.Name}WriteRepository : I{entity.Name}WriteRepository
    {{
        private readonly WriteDbContext _context;

        public {entity.Name}WriteRepository(WriteDbContext context)
        {{
            _context = context;
        }}

        public async Task AddAsync({entity.Name} entity)
        {{
            await _context.Set<{entity.Name}>().AddAsync(entity);
        }}

        public async Task UpdateAsync({entity.Name} entity)
        {{
            _context.Set<{entity.Name}>().Update(entity);
        }}

        public async Task DeleteAsync(int id)
        {{
            var entity = await _context.Set<{entity.Name}>().FindAsync(id);
            if (entity != null)
                _context.Set<{entity.Name}>().Remove(entity);
        }}
    }}
}}";
}

private string GenerateDistributedTransaction(EntityInfo entity)
{
    return $@"// <auto-generated/>
using Dtmcli;
using {entity.Namespace}.Domain.Events;

namespace {entity.Namespace}.Application.Transactions
{{
    public class {entity.Name}TransactionCoordinator
    {{
        private readonly IDtmClient _dtmClient;
        private readonly I{entity.Name}Repository _repository;

        public {entity.Name}TransactionCoordinator(
            IDtmClient dtmClient,
            I{entity.Name}Repository repository)
        {{
            _dtmClient = dtmClient;
            _repository = repository;
        }}

        public async Task ExecuteTransactionAsync({entity.Name} entity, params Func<Task>[] participants)
        {{
            var gid = await _dtmClient.GenGidAsync();
            using var saga = _dtmClient.NewSaga(gid)
                .Add(_repository.GetExecuteUpdateSql(entity), _repository.GetCompensateUpdateSql(entity));

            foreach (var participant in participants)
            {{
                saga.Add(await participant());
            }}

            await saga.SubmitAsync();
        }}
    }}
}}";
}

private string GenerateMauiPage(EntityInfo entity)
{
    return $@"// <auto-generated/>
using {entity.Namespace}.Application.Dtos;
using {entity.Namespace}.Application.Interfaces;

namespace {entity.Namespace}.Maui.Pages
{{
    public partial class {entity.Name}Page : ContentPage
    {{
        private readonly I{entity.Name}AppService _service;
        private ObservableCollection<{entity.Name}Dto> items = new();

        public {entity.Name}Page(I{entity.Name}AppService service)
        {{
            _service = service;
            InitializeComponent();
            LoadData();
        }}

        private async void LoadData()
        {{
            items.Clear();
            foreach(var item in await _service.GetAllAsync())
                items.Add(item);
        }}

        private async void OnAddClicked(object sender, EventArgs e)
        {{
            await Navigation.PushAsync(new {entity.Name}DetailPage(new {entity.Name}Dto(), _service));
        }}

        private async void OnItemSelected(object sender, SelectedItemChangedEventArgs e)
        {{
            if(e.SelectedItem is {entity.Name}Dto selected)
                await Navigation.PushAsync(new {entity.Name}DetailPage(selected, _service));
        }}
    }}
}}";
}

// 4. 高性能网络传输管道
[Generator]
public class PipeNetworkGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new PipeSyntaxReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (!(context.SyntaxContextReceiver is PipeSyntaxReceiver receiver))
            return;

        foreach (var service in receiver.Services)
        {
            var source = GeneratePipeService(service);
            context.AddSource($"{service.Name}PipeService.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    private string GeneratePipeService(ServiceInfo service)
    {
        return $@"// <auto-generated/>
using System.IO.Pipelines;
using System.Threading.Tasks;
using {service.Namespace}.Application.Interfaces;

namespace {service.Namespace}.Infrastructure.Pipes
{{
    public class {service.Name}PipeService
    {{
        private readonly Pipe _pipe;
        private readonly I{service.Name}AppService _appService;

        public {service.Name}PipeService(I{service.Name}AppService appService)
        {{
            _appService = appService;
            _pipe = new Pipe(new PipeOptions(
                pauseWriterThreshold: 1024 * 1024,
                resumeWriterThreshold: 512 * 1024,
                minimumSegmentSize: 4096));
            
            _ = ProcessPipeAsync();
        }}

        private async Task ProcessPipeAsync()
        {{
            while (true)
            {{
                var result = await _pipe.Reader.ReadAsync();
                var buffer = result.Buffer;
                
                // 处理数据...
                _pipe.Reader.AdvanceTo(buffer.End);
            }}
        }}
    }}
}}";
    }
}

// 5. 异步处理管道
[Generator]
public class ChannelProcessorGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new ChannelSyntaxReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (!(context.SyntaxContextReceiver is ChannelSyntaxReceiver receiver))
            return;

        foreach (var entity in receiver.Entities)
        {
            var source = GenerateChannelProcessor(entity);
            context.AddSource($"{entity.Name}ChannelProcessor.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    private string GenerateChannelProcessor(EntityInfo entity)
    {
        return $@"// <auto-generated/>
using System.Threading.Channels;
using System.Threading.Tasks;
using MediatR;
using {entity.Namespace}.Domain.Events;

namespace {entity.Namespace}.Infrastructure.Channels
{{
    public class {entity.Name}ChannelProcessor
    {{
        private readonly Channel<I{entity.Name}DomainEvent> _channel;
        private readonly IMediator _mediator;

        public {entity.Name}ChannelProcessor(IMediator mediator)
        {{
            _mediator = mediator;
            _channel = Channel.CreateBounded<I{entity.Name}DomainEvent>(new BoundedChannelOptions(1000)
            {{
                SingleWriter = false,
                SingleReader = true,
                FullMode = BoundedChannelFullMode.Wait
            }});
            
            _ = ProcessChannelAsync();
        }}

        public async ValueTask PublishAsync(I{entity.Name}DomainEvent @event)
        {{
            await _channel.Writer.WriteAsync(@event);
        }}

        private async Task ProcessChannelAsync()
        {{
            await foreach (var @event in _channel.Reader.ReadAllAsync())
            {{
                await _mediator.Publish(@event);
            }}
        }}
    }}
}}";
    }
}

// 6. 对象池优化
[Generator]
public class ObjectPoolGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new PoolSyntaxReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (!(context.SyntaxContextReceiver is PoolSyntaxReceiver receiver))
            return;

        foreach (var model in receiver.Models)
        {
            var source = GenerateObjectPool(model);
            context.AddSource($"{model.Name}ObjectPool.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    private string GenerateObjectPool(ModelInfo model)
    {
        return $@"// <auto-generated/>
using Microsoft.Extensions.ObjectPool;
using System.Buffers;

namespace {model.Namespace}.Infrastructure.Pools
{{
    public class {model.Name}ObjectPool
    {{
        private readonly ObjectPool<{model.Name}> _objectPool;
        private readonly ObjectPool<byte[]> _bufferPool;

        public {model.Name}ObjectPool()
        {{
            var policy = new DefaultPooledObjectPolicy<{model.Name}>();
            _objectPool = new DefaultObjectPool<{model.Name}>(policy, Environment.ProcessorCount * 2);
            
            _bufferPool = new DefaultObjectPool<byte[]>(
                new ArrayPooledObjectPolicy(), 
                Environment.ProcessorCount * 4);
        }}

        public {model.Name} Rent()
        {{
            return _objectPool.Get();
        }}

        public void Return({model.Name} obj)
        {{
            _objectPool.Return(obj);
        }}

        public byte[] RentBuffer()
        {{
            return _bufferPool.Get();
        }}

        public void ReturnBuffer(byte[] buffer)
        {{
            _bufferPool.Return(buffer);
        }}
    }}

    internal class ArrayPooledObjectPolicy : IPooledObjectPolicy<byte[]>
    {{
        public byte[] Create()
        {{
            return ArrayPool<byte>.Shared.Rent(4096);
        }}

        public bool Return(byte[] obj)
        {{
            ArrayPool<byte>.Shared.Return(obj);
            return true;
        }}
    }}
}}";
    }
}

// 增强生成器 - 添加VSA架构支持
private string GenerateVsaEndpoint(EntityInfo entity)
{
    return $@"// <auto-generated/>
using FastEndpoints;
using {entity.Namespace}.Application.Dtos;
using {entity.Namespace}.Application.Interfaces;
using System.Threading.Channels;
using Microsoft.Extensions.ObjectPool;
using System.Buffers;

namespace {entity.Namespace}.Api.Endpoints
{{
    public class {entity.Name}Endpoint : Endpoint<{entity.Name}Request, {entity.Name}Response>
    {{
        private readonly I{entity.Name}AppService _service;
        private readonly Channel<{entity.Name}Event> _channel;
        private readonly ObjectPool<Memory<byte>> _memoryPool;
        private readonly TailLatencyOptimizer _latencyOptimizer;

        public {entity.Name}Endpoint(
            I{entity.Name}AppService service,
            Channel<{entity.Name}Event> channel,
            ObjectPool<Memory<byte>> memoryPool,
            TailLatencyOptimizer latencyOptimizer)
        {{
            _service = service;
            _channel = channel;
            _memoryPool = memoryPool;
            _latencyOptimizer = latencyOptimizer;
        }}

        public override void Configure()
        {{
            Verbs(Http.POST);
            Routes(""/api/{entity.Name.ToLower()}"");
            Description(b => b
                .Produces<{entity.Name}Response>(201)
                .ProducesProblem(400));
        }}

        public override async Task HandleAsync({entity.Name}Request req, CancellationToken ct)
        {{
            _latencyOptimizer.Optimize(() =>
            {{
                var memory = _memoryPool.Get();
                try
                {{
                    // 使用Span零拷贝处理
                    var span = memory.Span;
                    // ... 高性能处理逻辑 ...
                }}
                finally
                {{
                    _memoryPool.Return(memory);
                }}
            }});

            var dto = Map.FromEntity(req);
            await _service.CreateAsync(dto);
            await _channel.Writer.WriteAsync(new {entity.Name}Event(dto.Id), ct);
            
            await SendCreatedAtAsync<Get{entity.Name}Endpoint>(
                new {{ id = dto.Id }}, 
                Map.FromEntity(dto),
                cancellation: ct);
        }}
    }}
}}";
}

// 生成Wolverine处理器
private string GenerateWolverineHandler(EntityInfo entity)
{
    return $@"// <auto-generated/>
using Wolverine;
using {entity.Namespace}.Domain.Events;
using System.Threading.Channels;
using System.Buffers;

namespace {entity.Namespace}.Application.Handlers
{{
    public class {entity.Name}EventHandler
    {{
        private readonly ChannelWriter<{entity.Name}Event> _writer;
        private readonly ThreadLocal<Span<byte>> _buffer;

        public {entity.Name}EventHandler(
            Channel<{entity.Name}Event> channel,
            ThreadLocal<Span<byte>> buffer)
        {{
            _writer = channel.Writer;
            _buffer = buffer;
        }}

        [WolverineHandler]
        public async Task Handle({entity.Name}CreatedEvent @event)
        {{
            // 使用线程专用内存处理
            Span<byte> buffer = _buffer.Value;
            // ... 高性能处理逻辑 ...
            
            await _writer.WriteAsync(new {entity.Name}Event(@event.Entity.Id));
        }}
    }}
}}";
}

// 生成Semantic Kernel集成
private string GenerateSemanticKernelIntegration(EntityInfo entity)
{
    return $@"// <auto-generated/>
using Microsoft.SemanticKernel;
using {entity.Namespace}.Domain.Entities;

namespace {entity.Namespace}.Application.Integrations
{{
    public class {entity.Name}SemanticKernelService
    {{
        private readonly IKernel _kernel;
        private readonly Channel<{entity.Name}Event> _channel;

        public {entity.Name}SemanticKernelService(
            IKernel kernel,
            Channel<{entity.Name}Event> channel)
        {{
            _kernel = kernel;
            _channel = channel;
            
            // 注册语义函数
            _kernel.ImportFunctions(new {entity.Name}Functions(), nameof({entity.Name}Functions));
        }}

        public async Task ProcessAsync({entity.Name} entity)
        {{
            var context = _kernel.CreateNewContext();
            context.Variables[""entity""] = System.Text.Json.JsonSerializer.Serialize(entity);
            
            await _kernel.RunAsync(
                context.Variables,
                _kernel.Functions.GetFunction(nameof({entity.Name}Functions), ""Process""));
                
            await _channel.Writer.WriteAsync(new {entity.Name}Event(entity.Id));
        }}
    }}
}}";
}