#:sdk Microsoft.NET.Sdk.Web
#:package WolverineFx@4.2.0
#:package WolverineFx.Marten@4.2.0
#:package WolverineFx.RDBMS@4.2.0
#:package WolverineFx.Postgresql@4.2.0
#:package WolverineFx.FluentValidation@4.2.0
#:package WolverineFx.Http@4.2.0
#:package WolverineFx.RabbitMQ@4.2.0
#:package WolverineFx.AzureServiceBus@4.2.0
#:package WolverineFx.Http.FluentValidation@4.2.0
#:package WolverineFx.Http.Marten@4.2.0
#:package WolverineFx.AmazonSqs@4.2.0
#:package WolverineFx.EntityFrameworkCore@4.2.0
#:package WolverineFx.SqlServer@4.2.0
#:package WolverineFx.Kafka@4.2.0
#:package WolverineFx.MemoryPack@4.2.0
#:package WolverineFx.MessagePack@4.2.0
#:package WolverineFx.MQTT@4.2.0
#:package WolverineFx.Pubsub@4.2.0
#:package WolverineFx.Pulsar@4.2.0
#:package WolverineFx.RavenDb@4.2.0
#:package Microsoft.CodeAnalysis.Common@4.14.0
#:package Microsoft.CodeAnalysis.Workspaces.Common@4.14.0
#:package Swashbuckle.AspNetCore@9.0.3
#:package Swashbuckle.AspNetCore.Swagger@9.0.3
#:package Swashbuckle.AspNetCore.SwaggerGen@9.0.3
#:package Swashbuckle.AspNetCore.SwaggerUI@9.0.3
#:package Microsoft.CodeAnalysis.Analyzers@4.14.0
#:package Microsoft.CodeAnalysis.CSharp@4.14.0
#:property LangVersion=preview
#:property TargetFramework=net11.0
#:property Nullable=enable
#:property ImplicitUsings=enable
#:property GenerateJsonSourceGeneration=true

//只写一次 业务意图（比如一个 [MessageContract] 标记的 interface），
// 编译时自动生成 record、属性、MessageBus 扩展方法，以及 Saga 状态（如果需要）.
// 生成的代码全部放在 obj/Generated，不需要手动编辑


using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace WolverineMessageGenerator;

// WolverineMessageGenerator/Generator.cs
[Generator]
public class MessageContractGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext ctx)
    {
        // 注册语法接收器，收集标记了 [MessageContract] 的接口
        ctx.RegisterForSyntaxNotifications(() => new InterfaceReceiver());
    }

    public void Execute(GeneratorExecutionContext ctx)
    {
        if (ctx.SyntaxReceiver is not InterfaceReceiver receiver) return;

        foreach (var iface in receiver.CandidateInterfaces)
        {
            var model = ctx.Compilation.GetSemanticModel(iface.SyntaxTree);
            var ifaceSymbol = model.GetDeclaredSymbol(iface) as INamedTypeSymbol;
            if (ifaceSymbol == null) continue;

            // 只处理标记了 MessageContractAttribute 的接口
            var hasAttr = ifaceSymbol.GetAttributes()
                .Any(a => a.AttributeClass?.Name == nameof(MessageContractAttribute));
            if (!hasAttr) continue;

            var source = GenerateCodeForInterface(ifaceSymbol);
            ctx.AddSource($"{ifaceSymbol.Name}_Generated.cs", source);
        }
    }

    private string GenerateCodeForInterface(INamedTypeSymbol iface)
    {
        var ns = iface.ContainingNamespace.ToDisplayString();
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using Wolverine;");
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();

        // 1️⃣ 为每个方法生成 Record（如果返回 void → Event）
        foreach (var m in iface.GetMembers().OfType<IMethodSymbol>())
        {
            var methodName = m.Name;
            var parameters = m.Parameters;
            var returnType = m.ReturnType;

            // 生成 record 名称
            var recordName = methodName;

            // 参数列表转成 record 属性
            var props = string.Join(", ",
                parameters.Select(p => $"{p.Type.ToDisplayString()} {p.Name}"));
            sb.AppendLine($"public sealed record {recordName}({props});");
            sb.AppendLine();

            // 如果返回值不是 void，生成 Response record
            if (!returnType.Name.Equals("Void"))
            {
                var respName = $"{recordName}Result";
                // 简单假设返回值是 primitive 或另一 record；这里直接转成属性
                // 为演示起见，使用单属性 Response（真实项目可自行扩展）
                sb.AppendLine($"public sealed record {respName}({returnType.ToDisplayString()} Result);");
                sb.AppendLine();
            }
        }

        // 2️⃣ 生成 MessageBus 扩展方法（帮助 Publish/Invoke）
        sb.AppendLine($"public static class {iface.Name}Extensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static IMessageBus GetBus(this IServiceProvider sp) => sp.GetService<IMessageBus>();");
        sb.AppendLine();

        foreach (var m in iface.GetMembers().OfType<IMethodSymbol>())
        {
            var methodName = m.Name;
            var parameters = m.Parameters;
            var returnType = m.ReturnType;
            var paramList = string.Join(", ", parameters.Select(p => $"{p.Type.ToDisplayString()} {p.Name}"));
            var argList   = string.Join(", ", parameters.Select(p => p.Name));

            // Publish (Event) 方法
            if (returnType.Name.Equals("Void"))
            {
                sb.AppendLine($"    public static async Task Publish{methodName}Async(this IServiceProvider sp, {paramList})");
                sb.AppendLine("    {");
                sb.AppendLine($"        var msg = new {methodName}({argList});");
                sb.AppendLine("        await sp.GetBus().PublishAsync(msg);");
                sb.AppendLine("    }");
                sb.AppendLine();
            }
            else // Request‑Response
            {
                var respRecord = $"{methodName}Result";
                sb.AppendLine($"    public static async Task<{respRecord}> Send{methodName}Async(this IServiceProvider sp, {paramList})");
                sb.AppendLine("    {");
                sb.AppendLine($"        var msg = new {methodName}({argList});");
                sb.AppendLine($"        return await sp.GetBus().InvokeAsync<{respRecord}>(msg);");
                sb.AppendLine("    }");
                sb.AppendLine();
            }
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    // -------------------------------------------------
    // 接收器：找到所有 interface 语法节点
    private class InterfaceReceiver : ISyntaxReceiver
    {
        public List<InterfaceDeclarationSyntax> CandidateInterfaces { get; } = new();

        public void OnVisitSyntaxNode(SyntaxNode node)
        {
            if (node is InterfaceDeclarationSyntax ids && ids.AttributeLists.Count > 0)
                CandidateInterfaces.Add(ids);
        }
    }
}

// Contracts/MessageDefinitions/IDeviceMessages.cs
namespace Contracts.Messages
{
    using Wolverine.MessageContracts;       // 只用于标记

    /// <summary>标记这是一个消息契约文件</summary>
    [MessageContract]                     // <-- 关键特性，Generator 会读取
    public interface IDeviceMessages
    {
        // 约定：在同一个 interface 里 方法名即为 Message 名称（PascalCase）.Method 参数会自动映射到 record 的属性，返回类型会被当作 Response（如果返回 void 则只生成 Event）
        // -------- 1️⃣ 请求/响应 ----------
        BindDeviceCommand Bind(Guid DeviceId, Guid UserId);
        BindDeviceResponse BindResult(Guid DeviceId, Guid UserId, bool Success, string? Error);

        // -------- 2️⃣ 领域事件 ----------
        DeviceBoundToUser DeviceBound(Guid DeviceId, Guid UserId, DateTimeOffset At);
        DeviceUnboundFromUser DeviceUnbound(Guid DeviceId, Guid UserId, DateTimeOffset At);
    }
}

// OutputItemType="Analyzer" 使得 Generator 参与编译，同时 Contracts 项目本身不需要显式引用生成的代码
//<ProjectReference Include="..\WolverineMessageGenerator\WolverineMessageGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />

// 生产的代码的使用
// 任意业务微服务（A/B/C）只引用 Contracts 项目
public class BindDeviceController : ControllerBase
{
    private readonly IServiceProvider _sp;
    public BindDeviceController(IServiceProvider sp) => _sp = sp;

    [HttpPost("bind")]
    public async Task<IActionResult> Bind([FromBody] BindRequest r)
    {
        var resp = await _sp.SendBindAsync(r.DeviceId, r.UserId); // 自动生成的扩展方法
        // var cmd = new BindDeviceCommand(r.DeviceId, r.UserId);
        // var resp = await bus.InvokeAsync<BindDeviceResult>(cmd);
        if (!resp.Result.Success)
            return BadRequest(resp.Result.Error);
        return Ok();
    }
}

// 同一套 .proto 既可以用于 Wolverine 消息总线，也可以直接提供 gRPC 接口（只需要在 *.proto 中定义 service，使用 Grpc.AspNetCore 即可）
// # 安装工具（只需要一次）
dotnet tool install -g protobuf-net.Tools

// # 编译 .proto → C#
dotnet pbnet compile -i Contracts/Protos/*.proto -o Contracts/Generated/Protos.cs
// pbnet 会把 string 映射为 string，我们在业务代码里约定把 Guid 用 Guid.Parse(string) 转换.

// GitHub Actions 示例
// 触发条件：Contracts 项目代码改动时，自动编译并发布到 GitHub Packages
name: Build & Publish Contracts

on:
  push:
    branches: [ main ]
    paths:
      - 'Contracts/**'          # 只在契约代码改动时触发

jobs:
  build-contracts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore
        run: dotnet restore Contracts/Contracts.csproj

      - name: Build (generates source)
        run: dotnet build Contracts/Contracts.csproj -c Release

      - name: Pack NuGet
        run: |
          dotnet pack Contracts/Contracts.csproj -c Release \
            -p:PackageVersion=1.$(date +%Y%m%d%H%M) \
            -o ./artifacts

      - name: Publish to GitHub Packages
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet nuget push ./artifacts/*.nupkg \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --api-key $NUGET_AUTH_TOKEN \
            --skip-duplicate
