#:sdk Microsoft.NET.Sdk
#:package Microsoft.CodeAnalysis.CSharp@4.7.0
#:package Microsoft.CodeAnalysis.Analyzers@3.3.4
#:package AutoMapper@12.0.1
#:package MediatR@12.1.1
#:property LangVersion preview
#:property TargetFramework net10.0
#:property Nullable enable
#:property ImplicitUsings enable

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

[Generator]
public class DddGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new DddSyntaxReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (!(context.SyntaxContextReceiver is DddSyntaxReceiver receiver))
            return;

        foreach (var entity in receiver.Entities)
        {
            // 1. 生成领域层代码
            GenerateDomainLayer(context, entity);
            
            // 2. 生成应用层代码
            GenerateApplicationLayer(context, entity);
            
            // 3. 生成基础设施层代码
            GenerateInfrastructureLayer(context, entity);
            
            // 4. 生成表示层代码
            GeneratePresentationLayer(context, entity);
        }
    }

    private void GenerateDomainLayer(GeneratorExecutionContext context, EntityInfo entity)
    {
        // 生成实体类
        var entitySource = $@"// <auto-generated/>
namespace {entity.Namespace}.Domain.Entities
{{
    public class {entity.Name}
    {{
        public int Id {{ get; private set; }}
        // ... 其他领域属性 ...
    }}
}}";
        context.AddSource($"{entity.Name}.g.cs", SourceText.From(entitySource, Encoding.UTF8));

        // 生成值对象
        var valueObjectSource = $@"// <auto-generated/>
namespace {entity.Namespace}.Domain.ValueObjects
{{
    public class {entity.Name}Id : ValueOf<int, {entity.Name}Id>
    {{
        protected override void Validate()
        {{
            if (Value <= 0)
                throw new ArgumentException(""ID必须大于0"");
        }}
    }}
}}";
        context.AddSource($"{entity.Name}Id.g.cs", SourceText.From(valueObjectSource, Encoding.UTF8));

        // 生成领域事件
        var domainEventSource = $@"// <auto-generated/>
using MediatR;

namespace {entity.Namespace}.Domain.Events
{{
    public class {entity.Name}CreatedEvent : INotification
    {{
        public {entity.Name} Entity {{ get; }}

        public {entity.Name}CreatedEvent({entity.Name} entity)
        {{
            Entity = entity;
        }}
    }}
}}";
        context.AddSource($"{entity.Name}CreatedEvent.g.cs", SourceText.From(domainEventSource, Encoding.UTF8));
    }

    private void GenerateApplicationLayer(GeneratorExecutionContext context, EntityInfo entity)
    {
        // 生成CQRS命令
        var commandSource = $@"// <auto-generated/>
using MediatR;
using {entity.Namespace}.Domain.Entities;

namespace {entity.Namespace}.Application.Commands
{{
    public record Create{entity.Name}Command({entity.Name} Entity) : IRequest<int>;
    public record Update{entity.Name}Command({entity.Name} Entity) : IRequest;
    public record Delete{entity.Name}Command(int Id) : IRequest;
}}";
        context.AddSource($"{entity.Name}Commands.g.cs", SourceText.From(commandSource, Encoding.UTF8));

        // 生成查询
        var querySource = $@"// <auto-generated/>
using MediatR;
using {entity.Namespace}.Application.Dtos;

namespace {entity.Namespace}.Application.Queries
{{
    public record Get{entity.Name}Query(int Id) : IRequest<{entity.Name}Dto>;
    public record GetAll{entityName}Query() : IRequest<IEnumerable<{entity.Name}Dto>>;
}}";
        context.AddSource($"{entity.Name}Queries.g.cs", SourceText.From(querySource, Encoding.UTF8));
    }

    // ... 其他生成方法 ...
}

public class DddSyntaxReceiver : ISyntaxContextReceiver
{
    public List<EntityInfo> Entities { get; } = new();

    public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
    {
        if (context.Node is ClassDeclarationSyntax classDecl && 
            classDecl.AttributeLists.Any(a => a.Attributes.Any(at => at.Name.ToString().Contains("Entity"))))
        {
            var model = context.SemanticModel.GetDeclaredSymbol(classDecl);
            if (model != null)
            {
                Entities.Add(new EntityInfo
                {
                    Name = model.Name,
                    Namespace = model.ContainingNamespace.ToDisplayString()
                });
            }
        }
    }
}

public class EntityInfo
{
    public string Name { get; set; }
    public string Namespace { get; set; }
}