<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PlcAiot.Shared\PlcAiot.Shared.csproj" />
    <ProjectReference Include="..\PlcAiot.Web.Client\PlcAiot.Web.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.0-preview.4.25258.110" />
    <PackageReference Include="MQTTnet" Version="4.3.7.1207" />
  </ItemGroup>

  <Target Name="CopyPages" BeforeTargets="Build">
    <ItemGroup>
      <PageFiles Include="..\..\pages\**\*" />
    </ItemGroup>
    <Copy SourceFiles="@(PageFiles)" DestinationFolder="wwwroot\pages\%(RecursiveDir)" SkipUnchangedFiles="true" />
  </Target>

</Project>
