<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0-windows</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>WorkerFlow</AssemblyName>
    <RootNamespace>WorkerFlow</RootNamespace>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CsGo\CsGo.csproj" />
  </ItemGroup>

</Project>
