#!/usr/bin/env dotnet
// <auto-generated/>
// ------------------------------------------------------------------------------
// <auto-generated by VSA Architecture Team>
// 生成时间: 2024-12-01
// 描述: 智能任务管理系统 - 优先级引擎实现
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System.Text.Json;
using System.ComponentModel;
using System.Diagnostics;
using System.Collections.Concurrent;
using System.Reflection;

namespace VSA.TodoSystem.Core;

/// <summary>
/// 优先级计算上下文
/// </summary>
public class PriorityCalculationContext
{
    public Guid TaskId { get; set; }
    
    public DateTimeOffset TaskCreatedAt { get; set; }
    
    public DateTimeOffset? DueDate { get; set; }
    
    public Priority OriginalPriority { get; set; }
    
    public int EstimatedHours { get; set; }
    
    public int ActualHours { get; set; }
    
    public int Progress { get; set; }
    
    public TaskCategory Category { get; set; }
    
    public TaskStatus Status { get; set; }
    
    public List<string> Tags { get; set; } = new();
    
    public int DependencyCount { get; set; }
    
    public int DependentCount { get; set; }
    
    public List<HistoricalData> HistoricalCompletionData { get; set; } = new();
    
    public TeamWorkload CurrentWorkload { get; set; } = new();
    
    public BusinessImpact BusinessImpact { get; set; } = new();
    
    public DeadlineProximity DeadlineProximity { get; set; } = new();
    
    public ResourceRequirements ResourceRequirements { get; set; } = new();
    
    public RiskAssessment RiskAssessment { get; set; } = new();
}

/// <summary>
/// 历史数据
/// </summary>
public class HistoricalData
{
    public DateTimeOffset CompletionDate { get; set; }
    
    public int EstimatedHours { get; set; }
    
    public int ActualHours { get; set; }
    
    public double CompletionRatio { get; set; }
    
    public Priority Priority { get; set; }
    
    public TaskCategory Category { get; set; }
    
    public bool WasOverdue { get; set; }
    
    public int DaysToComplete { get; set; }
}

/// <summary>
/// 团队工作负载
/// </summary>
public class TeamWorkload
{
    public Guid AssigneeId { get; set; }
    
    public string AssigneeName { get; set; } = string.Empty;
    
    public int CurrentTasks { get; set; }
    
    public int CurrentHighPriorityTasks { get; set; }
    
    public int TotalEstimatedHours { get; set; }
    
    public int AverageDailyCapacity { get; set; }
    
    public double WorkloadRatio { get; set; }
    
    public DateTimeOffset LastActivity { get; set; }
    
    public double PerformanceScore { get; set; } // 0-1, 基于历史表现
}

/// <summary>
/// 业务影响
/// </summary>
public class BusinessImpact
{
    public double RevenueImpact { get; set; } // 0-1, 收入影响
    
    public double CustomerImpact { get; set; } // 0-1, 客户影响
    
    public double StrategicImportance { get; set; } // 0-1, 战略重要性
    
    public double ComplianceRisk { get; set; } // 0-1, 合规风险
    
    public double TechnicalDebt { get; set; } // 0-1, 技术债务
    
    public double SecurityImpact { get; set; } // 0-1, 安全影响
    
    public double PerformanceImpact { get; set; } // 0-1, 性能影响
    
    public List<string> BusinessKeywords { get; set; } = new();
    
    public bool IsCustomerFacing { get; set; }
    
    public bool IsRevenueGenerating { get; set; }
}

/// <summary>
/// 截止日期接近度
/// </summary>
public class DeadlineProximity
{
    public TimeSpan TimeToDeadline { get; set; }
    
    public double ProximityScore { get; set; } // 0-1, 越接近截止日期分数越高
    
    public bool IsOverdue { get; set; }
    
    public double UrgencyMultiplier { get; set; } // 1.0-3.0, 紧急程度倍数
    
    public DateTimeOffset? NextWorkingDay { get; set; }
    
    public bool IsWeekend { get; set; }
    
    public bool IsHoliday { get; set; }
}

/// <summary>
/// 资源需求
/// </summary>
public class ResourceRequirements
{
    public int RequiredSkills { get; set; }
    
    public List<string> RequiredSkillTypes { get; set; } = new();
    
    public int ResourceAvailability { get; set; } // 0-100, 资源可用性百分比
    
    public bool RequiresSpecialist { get; set; }
    
    public bool IsCrossTeam { get; set; }
    
    public int EstimatedResourceDays { get; set; }
    
    public double ResourceCost { get; set; } // 相对成本
}

/// <summary>
/// 风险评估
/// </summary>
public class RiskAssessment
{
    public double TechnicalComplexity { get; set; } // 0-1, 技术复杂度
    
    public double ImplementationRisk { get; set; } // 0-1, 实现风险
    
    public double DependencyRisk { get; set; } // 0-1, 依赖风险
    
    public double QualityRisk { get; set; } // 0-1, 质量风险
    
    public double TimelineRisk { get; set; } // 0-1, 时间线风险
    
    public List<string> RiskFactors { get; set; } = new();
    
    public bool IsHighRisk { get; set; }
    
    public bool HasMitigationPlan { get; set; }
}

/// <summary>
/// 优先级权重配置
/// </summary>
public class PriorityWeights
{
    public double UrgencyWeight { get; set; } = 0.25; // 紧急性权重
    
    public double ImportanceWeight { get; set; } = 0.20; // 重要性权重
    
    public double BusinessImpactWeight { get; set; } = 0.20; // 业务影响权重
    
    public double ResourceAvailabilityWeight { get; set; } = 0.15; // 资源可用性权重
    
    public double RiskWeight { get; set; } = 0.10; // 风险权重
    
    public double WorkloadWeight { get; set; } = 0.10; // 工作负载权重
}

/// <summary>
/// 优先级计算结果
/// </summary>
public class PriorityResult
{
    public double CalculatedScore { get; set; }
    
    public Priority SuggestedPriority { get; set; }
    
    public Priority Reasoning { get; set; }
    
    public Dictionary<string, double> FactorScores { get; set; } = new();
    
    public List<string> Recommendations { get; set; } = new();
    
    public double Confidence { get; set; } // 0-1, 算法置信度
    
    public DateTimeOffset CalculatedAt { get; set; } = DateTimeOffset.UtcNow;
}

/// <summary>
/// 优先级策略接口
/// </summary>
public interface IPriorityStrategy
{
    Task<double> CalculateScoreAsync(PriorityCalculationContext context, CancellationToken cancellationToken = default);
    
    string StrategyName { get; }
    
    PriorityWeights Weights { get; }
}

/// <summary>
/// 紧急性优先级策略
/// </summary>
public class UrgencyPriorityStrategy : IPriorityStrategy
{
    public string StrategyName => "紧急性优先级策略";
    
    public PriorityWeights Weights => new PriorityWeights
    {
        UrgencyWeight = 0.4,
        ImportanceWeight = 0.2,
        BusinessImpactWeight = 0.2,
        ResourceAvailabilityWeight = 0.1,
        RiskWeight = 0.05,
        WorkloadWeight = 0.05
    };
    
    public async Task<double> CalculateScoreAsync(PriorityCalculationContext context, CancellationToken cancellationToken = default)
    {
        var score = 0.0;
        
        // 截止日期接近度 (40%)
        var deadlineScore = CalculateDeadlineScore(context);
        score += deadlineScore * 0.4;
        
        // 业务影响 (20%)
        var businessScore = CalculateBusinessImpactScore(context);
        score += businessScore * 0.2;
        
        // 重要性 (20%)
        var importanceScore = CalculateImportanceScore(context);
        score += importanceScore * 0.2;
        
        // 资源可用性 (10%)
        var resourceScore = CalculateResourceScore(context);
        score += resourceScore * 0.1;
        
        // 风险 (10%)
        var riskScore = CalculateRiskScore(context);
        score += riskScore * 0.1;
        
        return Math.Clamp(score, 0, 1);
    }
    
    private double CalculateDeadlineScore(PriorityCalculationContext context)
    {
        if (!context.DueDate.HasValue) return 0.5;
        
        var now = DateTimeOffset.UtcNow;
        var timeToDeadline = context.DueDate.Value - now;
        
        if (timeToDeadline.TotalDays < 0) return 1.0; // 已过期，最高优先级
        
        if (timeToDeadline.TotalDays <= 1) return 0.9; // 1天内
        
        if (timeToDeadline.TotalDays <= 3) return 0.7; // 3天内
        
        if (timeToDeadline.TotalDays <= 7) return 0.5; // 1周内
        
        if (timeToDeadline.TotalDays <= 30) return 0.3; // 1月内
        
        return 0.1; // 超过1个月
    }
    
    private double CalculateBusinessImpactScore(PriorityCalculationContext context)
    {
        var impact = context.BusinessImpact;
        return (impact.RevenueImpact + impact.CustomerImpact + impact.StrategicImportance) / 3.0;
    }
    
    private double CalculateImportanceScore(PriorityCalculationContext context)
    {
        // 基于任务分类、标签和状态计算重要性
        var categoryImportance = GetCategoryImportance(context.Category);
        var tagImportance = CalculateTagImportance(context.Tags);
        var statusImportance = GetStatusImportance(context.Status);
        
        return (categoryImportance + tagImportance + statusImportance) / 3.0;
    }
    
    private double CalculateResourceScore(PriorityCalculationContext context)
    {
        var requirements = context.ResourceRequirements;
        return requirements.ResourceAvailability / 100.0;
    }
    
    private double CalculateRiskScore(PriorityCalculationContext context)
    {
        var risk = context.RiskAssessment;
        return (risk.TechnicalComplexity + risk.ImplementationRisk + risk.DependencyRisk) / 3.0;
    }
    
    private double GetCategoryImportance(TaskCategory category)
    {
        return category switch
        {
            TaskCategory.Development => 0.8,
            TaskCategory.Maintenance => 0.6,
            TaskCategory.Research => 0.5,
            TaskCategory.Design => 0.7,
            TaskCategory.Documentation => 0.4,
            TaskCategory.Testing => 0.7,
            TaskCategory.Meeting => 0.3,
            TaskCategory.Other => 0.5,
            _ => 0.5
        };
    }
    
    private double CalculateTagImportance(List<string> tags)
    {
        if (!tags.Any()) return 0.5;
        
        var importantTags = new[] { "critical", "urgent", "production", "customer", "security", "performance" };
        var tagImportance = tags.Where(tag => importantTags.Contains(tag.ToLower())).Count() / (double)tags.Count;
        
        return Math.Max(tagImportance, 0.5);
    }
    
    private double GetStatusImportance(TaskStatus status)
    {
        return status switch
        {
            TaskStatus.Blocked => 1.0,
            TaskStatus.InProgress => 0.8,
            TaskStatus.Pending => 0.6,
            TaskStatus.Paused => 0.4,
            TaskStatus.Completed => 0.2,
            TaskStatus.Cancelled => 0.1,
            _ => 0.5
        };
    }
}

/// <summary>
/// 重要性优先级策略
/// </summary>
public class ImportancePriorityStrategy : IPriorityStrategy
{
    public string StrategyName => "重要性优先级策略";
    
    public PriorityWeights Weights => new PriorityWeights
    {
        UrgencyWeight = 0.15,
        ImportanceWeight = 0.35,
        BusinessImpactWeight = 0.25,
        ResourceAvailabilityWeight = 0.15,
        RiskWeight = 0.05,
        WorkloadWeight = 0.05
    };
    
    public async Task<double> CalculateScoreAsync(PriorityCalculationContext context, CancellationToken cancellationToken = default)
    {
        var score = 0.0;
        
        // 重要性 (35%)
        var importanceScore = CalculateImportanceScore(context);
        score += importanceScore * 0.35;
        
        // 业务影响 (25%)
        var businessScore = CalculateBusinessImpactScore(context);
        score += businessScore * 0.25;
        
        // 截止日期 (15%)
        var deadlineScore = CalculateDeadlineScore(context);
        score += deadlineScore * 0.15;
        
        // 资源可用性 (15%)
        var resourceScore = CalculateResourceScore(context);
        score += resourceScore * 0.15;
        
        // 工作负载 (5%)
        var workloadScore = CalculateWorkloadScore(context);
        score += workloadScore * 0.05;
        
        // 风险 (5%)
        var riskScore = CalculateRiskScore(context);
        score += riskScore * 0.05;
        
        return Math.Clamp(score, 0, 1);
    }
    
    private double CalculateImportanceScore(PriorityCalculationContext context)
    {
        var categoryImportance = GetCategoryImportance(context.Category);
        var dependencyImportance = CalculateDependencyImportance(context.DependencyCount, context.DependentCount);
        var resourceImportance = CalculateResourceImportance(context.ResourceRequirements);
        
        return (categoryImportance + dependencyImportance + resourceImportance) / 3.0;
    }
    
    private double CalculateBusinessImpactScore(PriorityCalculationContext context)
    {
        var impact = context.BusinessImpact;
        var weights = new[] { impact.RevenueImpact, impact.CustomerImpact, impact.StrategicImportance, impact.SecurityImpact };
        return weights.Average();
    }
    
    private double CalculateDeadlineScore(PriorityCalculationContext context)
    {
        if (!context.DueDate.HasValue) return 0.3;
        
        var now = DateTimeOffset.UtcNow;
        var timeToDeadline = context.DueDate.Value - now;
        
        if (timeToDeadline.TotalDays < 0) return 1.0;
        if (timeToDeadline.TotalDays <= 7) return 0.8;
        if (timeToDeadline.TotalDays <= 30) return 0.6;
        if (timeToDeadline.TotalDays <= 90) return 0.4;
        
        return 0.2;
    }
    
    private double CalculateResourceScore(PriorityCalculationContext context)
    {
        var requirements = context.ResourceRequirements;
        return requirements.ResourceAvailability / 100.0;
    }
    
    private double CalculateWorkloadScore(PriorityCalculationContext context)
    {
        var workload = context.CurrentWorkload;
        return 1.0 - workload.WorkloadRatio; // 工作负载越低，分数越高
    }
    
    private double CalculateRiskScore(PriorityCalculationContext context)
    {
        var risk = context.RiskAssessment;
        return 1.0 - (risk.TechnicalComplexity + risk.ImplementationRisk) / 2.0;
    }
    
    private double GetCategoryImportance(TaskCategory category)
    {
        return category switch
        {
            TaskCategory.Maintenance => 0.9, // 维护通常重要
            TaskCategory.Development => 0.8,
            TaskCategory.Security => 0.95,
            TaskCategory.Research => 0.6,
            TaskCategory.Design => 0.7,
            TaskCategory.Documentation => 0.4,
            TaskCategory.Testing => 0.7,
            TaskCategory.Meeting => 0.3,
            TaskCategory.Other => 0.5,
            _ => 0.5
        };
    }
    
    private double CalculateDependencyImportance(int dependencyCount, int dependentCount)
    {
        var totalDependencies = dependencyCount + dependentCount;
        return Math.Min(totalDependencies / 10.0, 1.0); // 最多10个依赖关系
    }
    
    private double CalculateResourceImportance(ResourceRequirements requirements)
    {
        var complexity = requirements.RequiredSkills / 5.0; // 标准化技能需求
        var availability = requirements.ResourceAvailability / 100.0;
        
        return (complexity + (1.0 - availability)) / 2.0; // 复杂度高且资源稀缺的任务更重要
    }
}

/// <summary>
/// 优先级计算器实现
/// </summary>
[System.ComponentModel.Description("智能优先级引擎")]
public class PriorityCalculator : IPriorityCalculator
{
    private readonly ILogger<PriorityCalculator> _logger;
    private readonly IMemoryCache _cache;
    private readonly List<IPriorityStrategy> _strategies;
    private readonly PriorityWeights _defaultWeights;
    
    public PriorityCalculator(
        ILogger<PriorityCalculator> logger,
        IMemoryCache cache)
    {
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        _cache = cache ?? throw new ArgumentNullException(nameof(cache));
        
        _strategies = new List<IPriorityStrategy>
        {
            new UrgencyPriorityStrategy(),
            new ImportancePriorityStrategy()
        };
        
        _defaultWeights = new PriorityWeights();
    }
    
    public async Task<double> CalculatePriorityAsync(TodoItem task, CancellationToken cancellationToken = default)
    {
        try
        {
            var context = await BuildCalculationContextAsync(task, cancellationToken);
            var strategies = SelectOptimalStrategies(context);
            
            var scores = new List<double>();
            var weights = new List<double>();
            
            foreach (var strategy in strategies)
            {
                var score = await strategy.CalculateScoreAsync(context, cancellationToken);
                scores.Add(score);
                weights.Add(GetStrategyWeight(strategy, context));
            }
            
            // 加权平均计算最终分数
            var weightedScore = scores.Zip(weights, (score, weight) => score * weight).Sum() / weights.Sum();
            
            _logger.LogDebug("优先级计算完成: {TaskId}, 分数: {Score:F3}", task.Id, weightedScore);
            
            return Math.Clamp(weightedScore, 0, 1);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "优先级计算失败: {TaskId}", task.Id);
            return 0.5; // 默认中等优先级
        }
    }
    
    public async Task<Priority> SuggestPriorityAsync(TodoItem task, CancellationToken cancellationToken = default)
    {
        var score = await CalculatePriorityAsync(task, cancellationToken);
        
        return ScoreToPriority(score);
    }
    
    public async Task<List<TodoItem>> ReorderByPriorityAsync(List<TodoItem> tasks, CancellationToken cancellationToken = default)
    {
        var taskScores = new List<(TodoItem Task, double Score)>();
        
        // 并行计算所有任务的优先级分数
        var semaphore = new SemaphoreSlim(Environment.ProcessorCount);
        var tasksToProcess = tasks.Select(async task =>
        {
            await semaphore.WaitAsync(cancellationToken);
            try
            {
                var score = await CalculatePriorityAsync(task, cancellationToken);
                return (Task: task, Score: score);
            }
            finally
            {
                semaphore.Release();
            }
        });
        
        var results = await Task.WhenAll(tasksToProcess);
        taskScores.AddRange(results.Where(r => r.Task != null));
        
        // 按分数降序排列
        return taskScores
            .OrderByDescending(ts => ts.Score)
            .Select(ts => ts.Task)
            .ToList();
    }
    
    public async Task<Dictionary<Priority, int>> GetPriorityDistributionAsync(List<TodoItem> tasks, CancellationToken cancellationToken = default)
    {
        var distribution = new Dictionary<Priority, int>();
        
        foreach (var task in tasks)
        {
            var suggestedPriority = await SuggestPriorityAsync(task, cancellationToken);
            distribution[suggestedPriority] = distribution.GetValueOrDefault(suggestedPriority, 0) + 1;
        }
        
        return distribution;
    }
    
    /// <summary>
    /// 计算详细的优先级结果
    /// </summary>
    public async Task<PriorityResult> CalculateDetailedPriorityAsync(TodoItem task, CancellationToken cancellationToken = default)
    {
        var context = await BuildCalculationContextAsync(task, cancellationToken);
        var strategies = SelectOptimalStrategies(context);
        
        var factorScores = new Dictionary<string, double>();
        var recommendations = new List<string>();
        var scores = new List<double>();
        var weights = new List<double>();
        
        foreach (var strategy in strategies)
        {
            var score = await strategy.CalculateScoreAsync(context, cancellationToken);
            scores.Add(score);
            weights.Add(GetStrategyWeight(strategy, context));
            
            // 收集因子分数
            factorScores[$"{strategy.StrategyName}_Score"] = score;
        }
        
        var weightedScore = scores.Zip(weights, (score, weight) => score * weight).Sum() / weights.Sum();
        var suggestedPriority = ScoreToPriority(weightedScore);
        var confidence = CalculateConfidence(factorScores, context);
        
        // 生成建议
        recommendations.AddRange(GenerateRecommendations(context, weightedScore, factorScores));
        
        return new PriorityResult
        {
            CalculatedScore = weightedScore,
            SuggestedPriority = suggestedPriority,
            Reasoning = suggestedPriority,
            FactorScores = factorScores,
            Recommendations = recommendations,
            Confidence = confidence
        };
    }
    
    // 私有辅助方法
    
    private async Task<PriorityCalculationContext> BuildCalculationContextAsync(TodoItem task, CancellationToken cancellationToken)
    {
        var context = new PriorityCalculationContext
        {
            TaskId = task.Id,
            TaskCreatedAt = task.CreatedAt,
            DueDate = task.DueDate,
            OriginalPriority = task.Priority,
            EstimatedHours = task.EstimatedHours,
            ActualHours = task.ActualHours,
            Progress = task.Progress,
            Category = task.Category,
            Status = task.Status,
            Tags = new List<string>(task.Tags),
            DependencyCount = task.Dependencies.Count,
            BusinessImpact = AnalyzeBusinessImpact(task),
            DeadlineProximity = AnalyzeDeadlineProximity(task),
            ResourceRequirements = AnalyzeResourceRequirements(task),
            RiskAssessment = AnalyzeRiskAssessment(task)
        };
        
        return context;
    }
    
    private List<IPriorityStrategy> SelectOptimalStrategies(PriorityCalculationContext context)
    {
        var selectedStrategies = new List<IPriorityStrategy>();
        
        // 基于截止日期紧急性选择策略
        if (context.DeadlineProximity.IsOverdue || context.DeadlineProximity.ProximityScore > 0.7)
        {
            selectedStrategies.Add(_strategies.First(s => s is UrgencyPriorityStrategy));
        }
        
        // 基于业务影响选择策略
        var totalBusinessImpact = context.BusinessImpact.RevenueImpact + 
                                 context.BusinessImpact.CustomerImpact + 
                                 context.BusinessImpact.StrategicImportance;
        
        if (totalBusinessImpact > 0.6)
        {
            selectedStrategies.Add(_strategies.First(s => s is ImportancePriorityStrategy));
        }
        
        // 如果没有特殊条件，使用默认策略
        if (!selectedStrategies.Any())
        {
            selectedStrategies.Add(_strategies.First()); // 使用第一个策略
        }
        
        return selectedStrategies;
    }
    
    private double GetStrategyWeight(IPriorityStrategy strategy, PriorityCalculationContext context)
    {
        var weights = strategy.Weights;
        
        // 根据任务特征调整权重
        if (context.DeadlineProximity.IsOverdue)
        {
            weights.UrgencyWeight *= 1.5; // 过期任务提高紧急性权重
        }
        
        if (context.BusinessImpact.RevenueImpact > 0.7)
        {
            weights.BusinessImpactWeight *= 1.3; // 高收入影响提高业务权重
        }
        
        if (context.RiskAssessment.IsHighRisk)
        {
            weights.RiskWeight *= 1.2; // 高风险提高风险权重
        }
        
        // 归一化权重
        var totalWeight = weights.UrgencyWeight + weights.ImportanceWeight + weights.BusinessImpactWeight +
                         weights.ResourceAvailabilityWeight + weights.RiskWeight + weights.WorkloadWeight;
        
        return 1.0 / _strategies.Count; // 所有策略权重相等
    }
    
    private Priority ScoreToPriority(double score)
    {
        return score switch
        {
            >= 0.9 => Priority.Critical,
            >= 0.7 => Priority.Urgent,
            >= 0.5 => Priority.High,
            >= 0.3 => Priority.Normal,
            _ => Priority.Low
        };
    }
    
    private double CalculateConfidence(Dictionary<string, double> factorScores, PriorityCalculationContext context)
    {
        // 基于数据完整性和一致性计算置信度
        var dataCompleteness = CalculateDataCompleteness(context);
        var scoreConsistency = CalculateScoreConsistency(factorScores);
        var historicalAccuracy = CalculateHistoricalAccuracy(context.HistoricalCompletionData);
        
        return (dataCompleteness + scoreConsistency + historicalAccuracy) / 3.0;
    }
    
    private double CalculateDataCompleteness(PriorityCalculationContext context)
    {
        var totalFields = 15; // 上下文中的字段总数
        var filledFields = 0;
        
        if (context.DueDate.HasValue) filledFields++;
        if (context.BusinessImpact.RevenueImpact > 0) filledFields++;
        if (context.BusinessImpact.CustomerImpact > 0) filledFields++;
        if (context.ResourceRequirements.RequiredSkills > 0) filledFields++;
        if (context.HistoricalCompletionData.Any()) filledFields++;
        if (context.Tags.Any()) filledFields++;
        if (context.DependencyCount > 0) filledFields++;
        if (context.DependentCount > 0) filledFields++;
        if (context.EstimatedHours > 0) filledFields++;
        if (context.Progress >= 0) filledFields++;
        
        return filledFields / (double)totalFields;
    }
    
    private double CalculateScoreConsistency(Dictionary<string, double> factorScores)
    {
        if (factorScores.Count < 2) return 1.0;
        
        var scores = factorScores.Values.ToList();
        var average = scores.Average();
        var variance = scores.Select(score => Math.Pow(score - average, 2)).Average();
        var standardDeviation = Math.Sqrt(variance);
        
        // 标准差越小，一致性越高
        return Math.Max(0, 1.0 - standardDeviation);
    }
    
    private double CalculateHistoricalAccuracy(List<HistoricalData> historicalData)
    {
        if (!historicalData.Any()) return 0.5; // 无历史数据时使用默认值
        
        var accuratePredictions = historicalData.Count(h => 
        {
            var estimatedRatio = h.EstimatedHours > 0 ? (double)h.ActualHours / h.EstimatedHours : 1.0;
            return estimatedRatio >= 0.8 && estimatedRatio <= 1.2; // 估算准确度在80%-120%范围内
        });
        
        return accuratePredictions / (double)historicalData.Count;
    }
    
    private List<string> GenerateRecommendations(PriorityCalculationContext context, double score, Dictionary<string, double> factorScores)
    {
        var recommendations = new List<string>();
        
        if (context.DeadlineProximity.IsOverdue)
        {
            recommendations.Add("任务已过期，建议立即处理或重新评估截止日期");
        }
        
        if (context.DeadlineProximity.ProximityScore > 0.8 && !context.DeadlineProximity.IsOverdue)
        {
            recommendations.Add("截止日期临近，建议优先安排处理");
        }
        
        if (context.BusinessImpact.RevenueImpact > 0.7)
        {
            recommendations.Add("此任务对收入有重大影响，建议提高优先级");
        }
        
        if (context.RiskAssessment.IsHighRisk)
        {
            recommendations.Add("任务存在高风险，建议制定详细的缓解计划");
        }
        
        if (context.DependencyCount > 5)
        {
            recommendations.Add("依赖关系过多，建议简化或分解任务");
        }
        
        if (context.CurrentWorkload.WorkloadRatio > 1.0)
        {
            recommendations.Add("当前工作负载过重，建议重新分配任务或延后非关键任务");
        }
        
        if (context.ResourceRequirements.RequiredSkills > 3)
        {
            recommendations.Add("需要多项技能，建议考虑团队协作或外部支持");
        }
        
        if (score > 0.8)
        {
            recommendations.Add("建议将此任务标记为高优先级并立即开始处理");
        }
        else if (score < 0.3)
        {
            recommendations.Add("此任务优先级较低，可以安排在低峰期处理");
        }
        
        return recommendations;
    }
    
    private BusinessImpact AnalyzeBusinessImpact(TodoItem task)
    {
        var impact = new BusinessImpact();
        
        // 分析标签中的业务关键词
        var businessKeywords = new[] { "revenue", "customer", "production", "critical", "security", "performance" };
        var matchingKeywords = task.Tags.Where(tag => 
            businessKeywords.Any(keyword => tag.ToLower().Contains(keyword))).ToList();
        
        impact.BusinessKeywords.AddRange(matchingKeywords);
        
        // 基于关键词和分类确定影响程度
        if (matchingKeywords.Contains("revenue") || matchingKeywords.Contains("customer"))
        {
            impact.RevenueImpact = 0.8;
            impact.CustomerImpact = 0.8;
            impact.IsRevenueGenerating = true;
        }
        
        if (matchingKeywords.Contains("security"))
        {
            impact.SecurityImpact = 0.9;
            impact.ComplianceRisk = 0.7;
        }
        
        if (matchingKeywords.Contains("performance"))
        {
            impact.PerformanceImpact = 0.8;
        }
        
        if (matchingKeywords.Contains("critical") || matchingKeywords.Contains("production"))
        {
            impact.StrategicImportance = 0.9;
        }
        
        // 基于分类调整影响
        impact.StrategicImportance = task.Category switch
        {
            TaskCategory.Maintenance => Math.Max(impact.StrategicImportance, 0.7),
            TaskCategory.Development => Math.Max(impact.StrategicImportance, 0.6),
            TaskCategory.Research => Math.Max(impact.StrategicImportance, 0.5),
            _ => impact.StrategicImportance
        };
        
        return impact;
    }
    
    private DeadlineProximity AnalyzeDeadlineProximity(TodoItem task)
    {
        var proximity = new DeadlineProximity();
        
        if (!task.DueDate.HasValue)
        {
            proximity.ProximityScore = 0.3; // 没有截止日期的任务默认为中等优先级
            return proximity;
        }
        
        var now = DateTimeOffset.UtcNow;
        proximity.TimeToDeadline = task.DueDate.Value - now;
        proximity.IsOverdue = proximity.TimeToDeadline.TotalDays < 0;
        
        if (proximity.IsOverdue)
        {
            proximity.ProximityScore = 1.0;
            proximity.UrgencyMultiplier = 2.0;
        }
        else
        {
            var daysToDeadline = proximity.TimeToDeadline.TotalDays;
            proximity.ProximityScore = Math.Max(0, 1.0 - (daysToDeadline / 30.0)); // 30天内线性衰减
            proximity.UrgencyMultiplier = daysToDeadline switch
            {
                <= 1 => 2.5,
                <= 3 => 2.0,
                <= 7 => 1.5,
                <= 14 => 1.2,
                <= 30 => 1.0,
                _ => 0.8
            };
        }
        
        return proximity;
    }
    
    private ResourceRequirements AnalyzeResourceRequirements(TodoItem task)
    {
        var requirements = new ResourceRequirements();
        
        // 基于任务分类估算技能需求
        requirements.RequiredSkills = task.Category switch
        {
            TaskCategory.Development => 2,
            TaskCategory.Maintenance => 1,
            TaskCategory.Research => 3,
            TaskCategory.Design => 2,
            TaskCategory.Testing => 2,
            TaskCategory.Meeting => 1,
            TaskCategory.Documentation => 1,
            _ => 1
        };
        
        // 基于标签确定技能类型
        var skillKeywords = new Dictionary<string, string[]>
        {
            ["backend"] = new[] { "csharp", "dotnet", "api", "database" },
            ["frontend"] = new[] { "javascript", "react", "angular", "css" },
            ["devops"] = new[] { "docker", "kubernetes", "ci", "cd" },
            ["security"] = new[] { "security", "authentication", "encryption" },
            ["database"] = new[] { "sql", "nosql", "migration", "optimization" }
        };
        
        foreach (var tag in task.Tags)
        {
            var lowerTag = tag.ToLower();
            foreach (var skillType in skillKeywords.Where(kvp => kvp.Value.Any(keyword => lowerTag.Contains(keyword))))
            {
                if (!requirements.RequiredSkillTypes.Contains(skillType.Key))
                {
                    requirements.RequiredSkillTypes.Add(skillType.Key);
                }
            }
        }
        
        // 基于复杂度估算资源可用性
        var complexity = (task.EstimatedHours + requirements.RequiredSkills) / 10.0;
        requirements.ResourceAvailability = Math.Max(20, 100 - (int)(complexity * 10));
        
        requirements.RequiresSpecialist = requirements.RequiredSkills > 2;
        requirements.IsCrossTeam = requirements.RequiredSkillTypes.Count > 2;
        requirements.EstimatedResourceDays = Math.Max(1, task.EstimatedHours / 8);
        
        return requirements;
    }
    
    private RiskAssessment AnalyzeRiskAssessment(TodoItem task)
    {
        var risk = new RiskAssessment();
        
        // 基于任务特征评估风险
        risk.TechnicalComplexity = Math.Min(1.0, task.EstimatedHours / 40.0); // 超过40小时的任务认为复杂度高
        
        risk.ImplementationRisk = task.Category switch
        {
            TaskCategory.Research => 0.8,
            TaskCategory.Development => 0.6,
            TaskCategory.Maintenance => 0.3,
            TaskCategory.Design => 0.4,
            TaskCategory.Testing => 0.5,
            _ => 0.5
        };
        
        risk.DependencyRisk = Math.Min(1.0, task.Dependencies.Count / 5.0); // 依赖越多风险越高
        
        // 基于标签识别风险因素
        var riskKeywords = new[] { "legacy", "critical", "production", "security", "performance", "experimental" };
        var riskTags = task.Tags.Where(tag => 
            riskKeywords.Any(keyword => tag.ToLower().Contains(keyword))).ToList();
        
        if (riskTags.Contains("legacy")) risk.TechnicalComplexity += 0.3;
        if (riskTags.Contains("critical")) risk.ImplementationRisk += 0.4;
        if (riskTags.Contains("production")) risk.QualityRisk += 0.5;
        if (riskTags.Contains("security")) risk.SecurityImpact += 0.6;
        
        risk.RiskFactors.AddRange(riskTags);
        risk.IsHighRisk = risk.TechnicalComplexity + risk.ImplementationRisk + risk.DependencyRisk > 2.0;
        
        return risk;
    }
}

/// <summary>
/// 优先级计算器扩展方法
/// </summary>
public static class PriorityCalculatorExtensions
{
    /// <summary>
    /// 批量计算任务优先级
    /// </summary>
    public static async Task<Dictionary<Guid, PriorityResult>> CalculateBatchPriorityAsync(
        this IPriorityCalculator calculator, 
        List<TodoItem> tasks, 
        CancellationToken cancellationToken = default)
    {
        var results = new Dictionary<Guid, PriorityResult>();
        var semaphore = new SemaphoreSlim(Environment.ProcessorCount);
        
        var tasksToProcess = tasks.Select(async task =>
        {
            await semaphore.WaitAsync(cancellationToken);
            try
            {
                if (calculator is PriorityCalculator priorityCalculator)
                {
                    var result = await priorityCalculator.CalculateDetailedPriorityAsync(task, cancellationToken);
                    return (TaskId: task.Id, Result: result);
                }
                return (TaskId: task.Id, Result: null as PriorityResult);
            }
            finally
            {
                semaphore.Release();
            }
        });
        
        var processedResults = await Task.WhenAll(tasksToProcess);
        
        foreach (var result in processedResults)
        {
            if (result.Result != null)
            {
                results[result.TaskId] = result.Result;
            }
        }
        
        return results;
    }
    
    /// <summary>
    /// 优化任务队列
    /// </summary>
    public static async Task<List<TodoItem>> OptimizeTaskQueueAsync(
        this IPriorityCalculator calculator,
        List<TodoItem> tasks,
        OptimizationCriteria criteria,
        CancellationToken cancellationToken = default)
    {
        var reorderedTasks = await calculator.ReorderByPriorityAsync(tasks, cancellationToken);
        
        // 根据优化标准进一步调整
        return criteria switch
        {
            OptimizationCriteria.MinimizeRisk => reorderedTasks.OrderBy(t => t.EstimatedHours).ToList(),
            OptimizationCriteria.MaximizeThroughput => reorderedTasks.OrderByDescending(t => t.EstimatedHours).ToList(),
            OptimizationCriteria.BalanceWorkload => reorderedTasks.OrderBy(t => t.AssigneeId.HasValue).ToList(),
            OptimizationCriteria.MinimizeDependencies => reorderedTasks.OrderBy(t => t.Dependencies.Count).ToList(),
            _ => reorderedTasks
        };
    }
}

/// <summary>
/// 优化标准
/// </summary>
public enum OptimizationCriteria
{
    Default,
    MinimizeRisk,
    MaximizeThroughput,
    BalanceWorkload,
    MinimizeDependencies
}

// 程序入口点
var builder = WebApplication.CreateBuilder(args);

// 配置服务
builder.Services.AddMemoryCache();
builder.Services.AddScoped<IPriorityCalculator, PriorityCalculator>();

// 添加Scrutor自动注册
builder.Services.Scan(scan => scan
    .FromAssemblies(Assembly.GetExecutingAssembly())
    .AddClasses(classes => classes.AssignableTo<IPriorityStrategy>())
    .AsImplementedInterfaces()
    .WithScopedLifetime());

// 配置应用
var app = builder.Build();

// 配置中间件
if (app.Environment.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
}

app.UseRouting();
app.UseEndpoints(endpoints =>
{
    endpoints.MapGet("/", () => "Priority Engine is running!");
    
    // 健康检查端点
    endpoints.MapGet("/health", () => Results.Ok(new { Status = "Healthy", Timestamp = DateTime.UtcNow }));
    
    // 优先级计算示例端点
    endpoints.MapPost("/calculate-priority", async (TodoItem task, IPriorityCalculator calculator) =>
    {
        var result = await calculator.CalculatePriorityAsync(task);
        return Results.Ok(new { Priority = result, SuggestedPriority = result switch
        {
            >= 0.9 => "Critical",
            >= 0.7 => "Urgent",
            >= 0.5 => "High",
            >= 0.3 => "Normal",
            _ => "Low"
        }});
    });
});

Console.WriteLine("Priority Engine started successfully!");
Console.WriteLine($"Environment: {app.Environment.EnvironmentName}");
Console.WriteLine("Available strategies: Urgency, Importance");
Console.WriteLine("Press Ctrl+C to shutdown");

app.Run();