#!/usr/bin/env dotnet
// <auto-generated/>
// ------------------------------------------------------------------------------
// <auto-generated by VSA Architecture Team>
// 生成时间: 2024-12-01
// 描述: 智能任务管理系统 - 核心任务服务实现
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Scrutor;
using System.Collections.Concurrent;
using System.Diagnostics;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Reflection;
using System.Text;

namespace VSA.TodoSystem.Core;

/// <summary>
/// 任务优先级枚举
/// </summary>
public enum Priority
{
    [Description("低优先级")]
    Low = 1,
    
    [Description("普通优先级")]
    Normal = 2,
    
    [Description("高优先级")]
    High = 3,
    
    [Description("紧急优先级")]
    Urgent = 4,
    
    [Description("关键优先级")]
    Critical = 5
}

/// <summary>
/// 任务状态枚举
/// </summary>
public enum TaskStatus
{
    [Description("待开始")]
    Pending = 0,
    
    [Description("进行中")]
    InProgress = 1,
    
    [Description("已完成")]
    Completed = 2,
    
    [Description("已取消")]
    Cancelled = 3,
    
    [Description("暂停")]
    Paused = 4,
    
    [Description("阻塞")]
    Blocked = 5
}

/// <summary>
/// 任务分类枚举
/// </summary>
public enum TaskCategory
{
    [Description("开发任务")]
    Development = 0,
    
    [Description("测试任务")]
    Testing = 1,
    
    [Description("设计任务")]
    Design = 2,
    
    [Description("文档任务")]
    Documentation = 3,
    
    [Description("会议任务")]
    Meeting = 4,
    
    [Description("研究任务")]
    Research = 5,
    
    [Description("维护任务")]
    Maintenance = 6,
    
    [Description("其他任务")]
    Other = 7
}

/// <summary>
/// 任务实体
/// </summary>
public class TodoItem
{
    public Guid Id { get; set; } = Guid.NewGuid();
    
    public string Title { get; set; } = string.Empty;
    
    public string? Description { get; set; }
    
    public Priority Priority { get; set; } = Priority.Normal;
    
    public TaskStatus Status { get; set; } = TaskStatus.Pending;
    
    public TaskCategory Category { get; set; } = TaskCategory.Other;
    
    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;
    
    public DateTimeOffset? DueDate { get; set; }
    
    public DateTimeOffset? StartedAt { get; set; }
    
    public DateTimeOffset? CompletedAt { get; set; }
    
    public DateTimeOffset? ModifiedAt { get; set; }
    
    public Guid? AssigneeId { get; set; }
    
    public string? AssigneeName { get; set; }
    
    public List<string> Tags { get; set; } = new();
    
    public List<Guid> Dependencies { get; set; } = new();
    
    public int EstimatedHours { get; set; }
    
    public int ActualHours { get; set; }
    
    public int Progress { get; set; } = 0;
    
    public string? Notes { get; set; }
    
    public bool IsRecurring { get; set; } = false;
    
    public string? RecurrencePattern { get; set; }
    
    public Dictionary<string, object> Metadata { get; set; } = new();
    
    public int Version { get; set; } = 1;
    
    public string? CreatedBy { get; set; }
    
    public string? ModifiedBy { get; set; }
}

/// <summary>
/// 创建任务命令
/// </summary>
public class CreateTodoCommand
{
    public string Title { get; set; } = string.Empty;
    
    public string? Description { get; set; }
    
    public Priority Priority { get; set; } = Priority.Normal;
    
    public TaskCategory Category { get; set; } = TaskCategory.Other;
    
    public DateTimeOffset? DueDate { get; set; }
    
    public Guid? AssigneeId { get; set; }
    
    public string? AssigneeName { get; set; }
    
    public List<string> Tags { get; set; } = new();
    
    public List<Guid> Dependencies { get; set; } = new();
    
    public int EstimatedHours { get; set; }
    
    public bool IsRecurring { get; set; } = false;
    
    public string? RecurrencePattern { get; set; }
    
    public string? CreatedBy { get; set; }
}

/// <summary>
/// 更新任务命令
/// </summary>
public class UpdateTodoCommand
{
    public Guid Id { get; set; }
    
    public string? Title { get; set; }
    
    public string? Description { get; set; }
    
    public Priority? Priority { get; set; }
    
    public TaskStatus? Status { get; set; }
    
    public TaskCategory? Category { get; set; }
    
    public DateTimeOffset? DueDate { get; set; }
    
    public Guid? AssigneeId { get; set; }
    
    public string? AssigneeName { get; set; }
    
    public List<string>? Tags { get; set; }
    
    public int? EstimatedHours { get; set; }
    
    public int? Progress { get; set; }
    
    public string? Notes { get; set; }
    
    public string? ModifiedBy { get; set; }
}

/// <summary>
/// 任务查询参数
/// </summary>
public class TodoQuery
{
    public TaskStatus? Status { get; set; }
    
    public Priority? Priority { get; set; }
    
    public TaskCategory? Category { get; set; }
    
    public Guid? AssigneeId { get; set; }
    
    public DateTimeOffset? DueDateFrom { get; set; }
    
    public DateTimeOffset? DueDateTo { get; set; }
    
    public string? SearchText { get; set; }
    
    public List<string>? Tags { get; set; }
    
    public int PageNumber { get; set; } = 1;
    
    public int PageSize { get; set; } = 50;
    
    public string? SortBy { get; set; }
    
    public bool SortDescending { get; set; } = false;
}

/// <summary>
/// 分页结果
/// </summary>
public class PagedResult<T>
{
    public List<T> Items { get; set; } = new();
    
    public int TotalCount { get; set; }
    
    public int PageNumber { get; set; }
    
    public int PageSize { get; set; }
    
    public int TotalPages => (int)Math.Ceiling((double)TotalCount / PageSize);
    
    public bool HasNextPage => PageNumber < TotalPages;
    
    public bool HasPreviousPage => PageNumber > 1;
}

/// <summary>
/// 任务统计信息
/// </summary>
public class TodoStatistics
{
    public int TotalTasks { get; set; }
    
    public int CompletedTasks { get; set; }
    
    public int InProgressTasks { get; set; }
    
    public int PendingTasks { get; set; }
    
    public int OverdueTasks { get; set; }
    
    public int CriticalTasks { get; set; }
    
    public int HighPriorityTasks { get; set; }
    
    public double CompletionRate { get; set; }
    
    public int AverageCompletionTime { get; set; }
    
    public Dictionary<Priority, int> TasksByPriority { get; set; } = new();
    
    public Dictionary<TaskStatus, int> TasksByStatus { get; set; } = new();
    
    public Dictionary<TaskCategory, int> TasksByCategory { get; set; } = new();
    
    public DateTime LastUpdated { get; set; } = DateTime.UtcNow;
}

/// <summary>
/// 任务服务接口
/// </summary>
public interface ITodoService
{
    Task<TodoItem> CreateAsync(CreateTodoCommand command, CancellationToken cancellationToken = default);
    
    Task<TodoItem?> GetByIdAsync(Guid id, CancellationToken cancellationToken = default);
    
    Task<PagedResult<TodoItem>> GetAllAsync(TodoQuery query, CancellationToken cancellationToken = default);
    
    Task<TodoItem> UpdateAsync(UpdateTodoCommand command, CancellationToken cancellationToken = default);
    
    Task<bool> DeleteAsync(Guid id, CancellationToken cancellationToken = default);
    
    Task<TodoItem> StartTaskAsync(Guid id, CancellationToken cancellationToken = default);
    
    Task<TodoItem> CompleteTaskAsync(Guid id, CancellationToken cancellationToken = default);
    
    Task<TodoItem> PauseTaskAsync(Guid id, CancellationToken cancellationToken = default);
    
    Task<TodoItem> ResumeTaskAsync(Guid id, CancellationToken cancellationToken = default);
    
    Task<List<TodoItem>> GetDependenciesAsync(Guid id, CancellationToken cancellationToken = default);
    
    Task<List<TodoItem>> GetDependentsAsync(Guid id, CancellationToken cancellationToken = default);
    
    Task<bool> AddDependencyAsync(Guid taskId, Guid dependencyId, CancellationToken cancellationToken = default);
    
    Task<bool> RemoveDependencyAsync(Guid taskId, Guid dependencyId, CancellationToken cancellationToken = default);
    
    Task<TodoStatistics> GetStatisticsAsync(CancellationToken cancellationToken = default);
    
    Task<List<TodoItem>> GetOverdueTasksAsync(CancellationToken cancellationToken = default);
    
    Task<List<TodoItem>> GetDueSoonTasksAsync(TimeSpan timeframe, CancellationToken cancellationToken = default);
    
    Task<Dictionary<string, object>> AnalyzeTaskPatternsAsync(Guid? userId = null, CancellationToken cancellationToken = default);
    
    Task<List<TodoItem>> GetTasksByAssigneeAsync(Guid assigneeId, CancellationToken cancellationToken = default);
    
    Task<TodoItem> CloneAsync(Guid id, string? newTitle = null, CancellationToken cancellationToken = default);
    
    Task<bool> ValidateTaskAsync(TodoItem task, CancellationToken cancellationToken = default);
    
    Task<List<TodoItem>> GetTasksForReviewAsync(TimeSpan timeframe, CancellationToken cancellationToken = default);
    
    Task<TodoStatistics> GetTeamStatisticsAsync(List<Guid> userIds, CancellationToken cancellationToken = default);
}

/// <summary>
/// 优先级计算器接口
/// </summary>
public interface IPriorityCalculator
{
    Task<double> CalculatePriorityAsync(TodoItem task, CancellationToken cancellationToken = default);
    
    Task<Priority> SuggestPriorityAsync(TodoItem task, CancellationToken cancellationToken = default);
    
    Task<List<TodoItem>> ReorderByPriorityAsync(List<TodoItem> tasks, CancellationToken cancellationToken = default);
    
    Task<Dictionary<Priority, int>> GetPriorityDistributionAsync(List<TodoItem> tasks, CancellationToken cancellationToken = default);
}

/// <summary>
/// 任务服务实现
/// </summary>
[Service(Lifetime = ServiceLifetime.Scoped)]
public class TodoService : ITodoService
{
    private readonly ITodoRepository _repository;
    private readonly IPriorityCalculator _priorityCalculator;
    private readonly IMemoryCache _cache;
    private readonly ILogger<TodoService> _logger;
    private readonly IEventBus _eventBus;
    private readonly Timer _cleanupTimer;
    
    private static readonly SemaphoreSlim _semaphore = new(1, 1);
    
    public TodoService(
        ITodoRepository repository,
        IPriorityCalculator priorityCalculator,
        IMemoryCache cache,
        ILogger<TodoService> logger,
        IEventBus eventBus)
    {
        _repository = repository ?? throw new ArgumentNullException(nameof(repository));
        _priorityCalculator = priorityCalculator ?? throw new ArgumentNullException(nameof(priorityCalculator));
        _cache = cache ?? throw new ArgumentNullException(nameof(cache));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        _eventBus = eventBus ?? throw new ArgumentNullException(nameof(eventBus));
        
        // 定时清理过期缓存
        _cleanupTimer = new Timer(CleanupCache, null, TimeSpan.FromMinutes(5), TimeSpan.FromMinutes(5));
    }
    
    public async Task<TodoItem> CreateAsync(CreateTodoCommand command, CancellationToken cancellationToken = default)
    {
        try
        {
            await _semaphore.WaitAsync(cancellationToken);
            
            var task = new TodoItem
            {
                Id = Guid.NewGuid(),
                Title = command.Title.Trim(),
                Description = command.Description?.Trim(),
                Priority = command.Priority,
                Category = command.Category,
                DueDate = command.DueDate,
                AssigneeId = command.AssigneeId,
                AssigneeName = command.AssigneeName?.Trim(),
                Tags = command.Tags.Distinct().ToList(),
                Dependencies = command.Dependencies.Distinct().ToList(),
                EstimatedHours = command.EstimatedHours,
                IsRecurring = command.IsRecurring,
                RecurrencePattern = command.RecurrencePattern,
                CreatedAt = DateTimeOffset.UtcNow,
                CreatedBy = command.CreatedBy,
                ModifiedAt = DateTimeOffset.UtcNow
            };
            
            // 验证任务
            var isValid = await ValidateTaskAsync(task, cancellationToken);
            if (!isValid)
            {
                throw new InvalidOperationException("任务验证失败");
            }
            
            // 检查依赖关系
            if (task.Dependencies.Any())
            {
                var dependencies = await _repository.GetByIdsAsync(task.Dependencies, cancellationToken);
                if (dependencies.Count != task.Dependencies.Count)
                {
                    throw new InvalidOperationException("部分依赖任务不存在");
                }
                
                // 检查循环依赖
                if (await HasCircularDependencyAsync(task.Id, task.Dependencies, cancellationToken))
                {
                    throw new InvalidOperationException("存在循环依赖关系");
                }
            }
            
            var createdTask = await _repository.CreateAsync(task, cancellationToken);
            
            // 发布事件
            await _eventBus.PublishAsync(new TodoCreatedEvent(createdTask), cancellationToken);
            
            // 清除相关缓存
            await ClearRelatedCacheAsync(createdTask, cancellationToken);
            
            _logger.LogInformation("任务创建成功: {TaskId}, 标题: {Title}", createdTask.Id, createdTask.Title);
            
            return createdTask;
        }
        finally
        {
            _semaphore.Release();
        }
    }
    
    public async Task<TodoItem?> GetByIdAsync(Guid id, CancellationToken cancellationToken = default)
    {
        var cacheKey = $"todo:{id}";
        
        if (_cache.TryGetValue(cacheKey, out TodoItem? cachedTask))
        {
            return cachedTask;
        }
        
        var task = await _repository.GetByIdAsync(id, cancellationToken);
        
        if (task != null)
        {
            _cache.Set(cacheKey, task, TimeSpan.FromMinutes(30));
        }
        
        return task;
    }
    
    public async Task<PagedResult<TodoItem>> GetAllAsync(TodoQuery query, CancellationToken cancellationToken = default)
    {
        var cacheKey = $"todos:query:{JsonSerializer.Serialize(query)}";
        
        if (_cache.TryGetValue(cacheKey, out PagedResult<TodoItem>? cachedResult))
        {
            return cachedResult;
        }
        
        var result = await _repository.GetPagedAsync(query, cancellationToken);
        
        _cache.Set(cacheKey, result, TimeSpan.FromMinutes(15));
        
        return result;
    }
    
    public async Task<TodoItem> UpdateAsync(UpdateTodoCommand command, CancellationToken cancellationToken = default)
    {
        try
        {
            await _semaphore.WaitAsync(cancellationToken);
            
            var existingTask = await GetByIdAsync(command.Id, cancellationToken);
            if (existingTask == null)
            {
                throw new KeyNotFoundException($"任务 {command.Id} 不存在");
            }
            
            var oldStatus = existingTask.Status;
            var oldPriority = existingTask.Priority;
            
            // 更新字段
            if (!string.IsNullOrWhiteSpace(command.Title))
                existingTask.Title = command.Title.Trim();
                
            if (command.Description != null)
                existingTask.Description = command.Description.Trim();
                
            if (command.Priority.HasValue)
                existingTask.Priority = command.Priority.Value;
                
            if (command.Status.HasValue)
            {
                existingTask.Status = command.Status.Value;
                
                if (command.Status == TaskStatus.InProgress && !existingTask.StartedAt.HasValue)
                {
                    existingTask.StartedAt = DateTimeOffset.UtcNow;
                }
                else if (command.Status == TaskStatus.Completed && !existingTask.CompletedAt.HasValue)
                {
                    existingTask.CompletedAt = DateTimeOffset.UtcNow;
                }
            }
            
            if (command.Category.HasValue)
                existingTask.Category = command.Category.Value;
                
            if (command.DueDate.HasValue)
                existingTask.DueDate = command.DueDate;
                
            if (command.AssigneeId.HasValue)
                existingTask.AssigneeId = command.AssigneeId;
                
            if (command.AssigneeName != null)
                existingTask.AssigneeName = command.AssigneeName.Trim();
                
            if (command.Tags != null)
                existingTask.Tags = command.Tags.Distinct().ToList();
                
            if (command.EstimatedHours.HasValue)
                existingTask.EstimatedHours = command.EstimatedHours.Value;
                
            if (command.Progress.HasValue)
                existingTask.Progress = Math.Clamp(command.Progress.Value, 0, 100);
                
            if (command.Notes != null)
                existingTask.Notes = command.Notes.Trim();
                
            existingTask.ModifiedAt = DateTimeOffset.UtcNow;
            existingTask.ModifiedBy = command.ModifiedBy;
            existingTask.Version++;
            
            // 验证更新后的任务
            var isValid = await ValidateTaskAsync(existingTask, cancellationToken);
            if (!isValid)
            {
                throw new InvalidOperationException("更新后的任务验证失败");
            }
            
            var updatedTask = await _repository.UpdateAsync(existingTask, cancellationToken);
            
            // 发布事件
            if (oldStatus != updatedTask.Status)
            {
                await _eventBus.PublishAsync(new TodoStatusChangedEvent(updatedTask, oldStatus), cancellationToken);
            }
            
            if (oldPriority != updatedTask.Priority)
            {
                await _eventBus.PublishAsync(new TodoPriorityChangedEvent(updatedTask, oldPriority), cancellationToken);
            }
            
            await _eventBus.PublishAsync(new TodoUpdatedEvent(updatedTask), cancellationToken);
            
            // 清除相关缓存
            await ClearRelatedCacheAsync(updatedTask, cancellationToken);
            
            _logger.LogInformation("任务更新成功: {TaskId}, 状态: {OldStatus} -> {NewStatus}", 
                updatedTask.Id, oldStatus, updatedTask.Status);
            
            return updatedTask;
        }
        finally
        {
            _semaphore.Release();
        }
    }
    
    public async Task<bool> DeleteAsync(Guid id, CancellationToken cancellationToken = default)
    {
        try
        {
            await _semaphore.WaitAsync(cancellationToken);
            
            var task = await GetByIdAsync(id, cancellationToken);
            if (task == null)
            {
                return false;
            }
            
            // 检查是否有其他任务依赖于此任务
            var dependents = await GetDependentsAsync(id, cancellationToken);
            if (dependents.Any())
            {
                throw new InvalidOperationException($"无法删除任务 {id}，因为有 {dependents.Count} 个任务依赖于它");
            }
            
            var deleted = await _repository.DeleteAsync(id, cancellationToken);
            
            if (deleted)
            {
                await _eventBus.PublishAsync(new TodoDeletedEvent(task), cancellationToken);
                
                // 清除缓存
                await ClearTaskCacheAsync(id, cancellationToken);
                
                _logger.LogInformation("任务删除成功: {TaskId}", id);
            }
            
            return deleted;
        }
        finally
        {
            _semaphore.Release();
        }
    }
    
    public async Task<TodoItem> StartTaskAsync(Guid id, CancellationToken cancellationToken = default)
    {
        var task = await GetByIdAsync(id, cancellationToken);
        if (task == null)
        {
            throw new KeyNotFoundException($"任务 {id} 不存在");
        }
        
        if (task.Status != TaskStatus.Pending && task.Status != TaskStatus.Paused)
        {
            throw new InvalidOperationException($"任务状态不正确，当前状态: {task.Status}");
        }
        
        // 检查依赖是否完成
        if (task.Dependencies.Any())
        {
            var dependencies = await _repository.GetByIdsAsync(task.Dependencies, cancellationToken);
            var incompleteDependencies = dependencies.Where(d => d.Status != TaskStatus.Completed).ToList();
            
            if (incompleteDependencies.Any())
            {
                throw new InvalidOperationException($"存在未完成的依赖任务: {string.Join(", ", incompleteDependencies.Select(d => d.Title))}");
            }
        }
        
        var command = new UpdateTodoCommand
        {
            Id = id,
            Status = TaskStatus.InProgress,
            StartedAt = DateTimeOffset.UtcNow,
            ModifiedBy = "system"
        };
        
        return await UpdateAsync(command, cancellationToken);
    }
    
    public async Task<TodoItem> CompleteTaskAsync(Guid id, CancellationToken cancellationToken = default)
    {
        var task = await GetByIdAsync(id, cancellationToken);
        if (task == null)
        {
            throw new KeyNotFoundException($"任务 {id} 不存在");
        }
        
        if (task.Status != TaskStatus.InProgress)
        {
            throw new InvalidOperationException($"任务状态不正确，当前状态: {task.Status}");
        }
        
        var command = new UpdateTodoCommand
        {
            Id = id,
            Status = TaskStatus.Completed,
            CompletedAt = DateTimeOffset.UtcNow,
            Progress = 100,
            ModifiedBy = "system"
        };
        
        var completedTask = await UpdateAsync(command, cancellationToken);
        
        // 如果是周期性任务，创建下一个实例
        if (completedTask.IsRecurring && !string.IsNullOrEmpty(completedTask.RecurrencePattern))
        {
            await CreateNextRecurringTaskAsync(completedTask, cancellationToken);
        }
        
        return completedTask;
    }
    
    public async Task<TodoItem> PauseTaskAsync(Guid id, CancellationToken cancellationToken = default)
    {
        var command = new UpdateTodoCommand
        {
            Id = id,
            Status = TaskStatus.Paused,
            ModifiedBy = "system"
        };
        
        return await UpdateAsync(command, cancellationToken);
    }
    
    public async Task<TodoItem> ResumeTaskAsync(Guid id, CancellationToken cancellationToken = default)
    {
        return await StartTaskAsync(id, cancellationToken);
    }
    
    public async Task<List<TodoItem>> GetDependenciesAsync(Guid id, CancellationToken cancellationToken = default)
    {
        var task = await GetByIdAsync(id, cancellationToken);
        if (task?.Dependencies == null || !task.Dependencies.Any())
        {
            return new List<TodoItem>();
        }
        
        return await _repository.GetByIdsAsync(task.Dependencies, cancellationToken);
    }
    
    public async Task<List<TodoItem>> GetDependentsAsync(Guid id, CancellationToken cancellationToken = default)
    {
        return await _repository.GetDependentsAsync(id, cancellationToken);
    }
    
    public async Task<bool> AddDependencyAsync(Guid taskId, Guid dependencyId, CancellationToken cancellationToken = default)
    {
        try
        {
            await _semaphore.WaitAsync(cancellationToken);
            
            if (taskId == dependencyId)
            {
                throw new InvalidOperationException("任务不能依赖于自己");
            }
            
            var task = await GetByIdAsync(taskId, cancellationToken);
            if (task == null)
            {
                throw new KeyNotFoundException($"任务 {taskId} 不存在");
            }
            
            var dependency = await GetByIdAsync(dependencyId, cancellationToken);
            if (dependency == null)
            {
                throw new KeyNotFoundException($"依赖任务 {dependencyId} 不存在");
            }
            
            if (task.Dependencies.Contains(dependencyId))
            {
                return false; // 已经存在依赖关系
            }
            
            // 检查循环依赖
            if (await HasCircularDependencyAsync(taskId, new List<Guid> { dependencyId }, cancellationToken))
            {
                throw new InvalidOperationException("添加此依赖会形成循环依赖");
            }
            
            task.Dependencies.Add(dependencyId);
            task.ModifiedAt = DateTimeOffset.UtcNow;
            
            await _repository.UpdateAsync(task, cancellationToken);
            await _eventBus.PublishAsync(new TodoDependencyAddedEvent(task, dependency), cancellationToken);
            
            await ClearTaskCacheAsync(taskId, cancellationToken);
            
            _logger.LogInformation("添加任务依赖成功: {TaskId} 依赖于 {DependencyId}", taskId, dependencyId);
            
            return true;
        }
        finally
        {
            _semaphore.Release();
        }
    }
    
    public async Task<bool> RemoveDependencyAsync(Guid taskId, Guid dependencyId, CancellationToken cancellationToken = default)
    {
        try
        {
            await _semaphore.WaitAsync(cancellationToken);
            
            var task = await GetByIdAsync(taskId, cancellationToken);
            if (task == null)
            {
                throw new KeyNotFoundException($"任务 {taskId} 不存在");
            }
            
            var removed = task.Dependencies.Remove(dependencyId);
            if (removed)
            {
                task.ModifiedAt = DateTimeOffset.UtcNow;
                
                await _repository.UpdateAsync(task, cancellationToken);
                await _eventBus.PublishAsync(new TodoDependencyRemovedEvent(task, dependencyId), cancellationToken);
                
                await ClearTaskCacheAsync(taskId, cancellationToken);
                
                _logger.LogInformation("移除任务依赖成功: {TaskId} 不再依赖于 {DependencyId}", taskId, dependencyId);
            }
            
            return removed;
        }
        finally
        {
            _semaphore.Release();
        }
    }
    
    public async Task<TodoStatistics> GetStatisticsAsync(CancellationToken cancellationToken = default)
    {
        var cacheKey = "todo:statistics:global";
        
        if (_cache.TryGetValue(cacheKey, out TodoStatistics? cachedStats))
        {
            return cachedStats;
        }
        
        var allTasks = await _repository.GetAllAsync(cancellationToken);
        var now = DateTimeOffset.UtcNow;
        
        var stats = new TodoStatistics
        {
            TotalTasks = allTasks.Count,
            CompletedTasks = allTasks.Count(t => t.Status == TaskStatus.Completed),
            InProgressTasks = allTasks.Count(t => t.Status == TaskStatus.InProgress),
            PendingTasks = allTasks.Count(t => t.Status == TaskStatus.Pending),
            OverdueTasks = allTasks.Count(t => t.DueDate.HasValue && t.DueDate < now && t.Status != TaskStatus.Completed),
            CriticalTasks = allTasks.Count(t => t.Priority == Priority.Critical),
            HighPriorityTasks = allTasks.Count(t => t.Priority == Priority.High),
            CompletionRate = allTasks.Count > 0 ? (double)allTasks.Count(t => t.Status == TaskStatus.Completed) / allTasks.Count * 100 : 0,
            TasksByPriority = allTasks.GroupBy(t => t.Priority).ToDictionary(g => g.Key, g => g.Count()),
            TasksByStatus = allTasks.GroupBy(t => t.Status).ToDictionary(g => g.Key, g => g.Count()),
            TasksByCategory = allTasks.GroupBy(t => t.Category).ToDictionary(g => g.Key, g => g.Count()),
            LastUpdated = DateTime.UtcNow
        };
        
        // 计算平均完成时间
        var completedTasks = allTasks.Where(t => t.Status == TaskStatus.Completed && t.StartedAt.HasValue && t.CompletedAt.HasValue).ToList();
        if (completedTasks.Any())
        {
            stats.AverageCompletionTime = (int)completedTasks.Average(t => (t.CompletedAt!.Value - t.StartedAt!.Value).TotalHours);
        }
        
        _cache.Set(cacheKey, stats, TimeSpan.FromMinutes(10));
        
        return stats;
    }
    
    public async Task<List<TodoItem>> GetOverdueTasksAsync(CancellationToken cancellationToken = default)
    {
        var allTasks = await _repository.GetAllAsync(cancellationToken);
        var now = DateTimeOffset.UtcNow;
        
        return allTasks.Where(t => 
            t.DueDate.HasValue && 
            t.DueDate < now && 
            t.Status != TaskStatus.Completed &&
            t.Status != TaskStatus.Cancelled)
            .OrderBy(t => t.DueDate)
            .ToList();
    }
    
    public async Task<List<TodoItem>> GetDueSoonTasksAsync(TimeSpan timeframe, CancellationToken cancellationToken = default)
    {
        var allTasks = await _repository.GetAllAsync(cancellationToken);
        var deadline = DateTimeOffset.UtcNow.Add(timeframe);
        
        return allTasks.Where(t => 
            t.DueDate.HasValue && 
            t.DueDate <= deadline && 
            t.Status != TaskStatus.Completed &&
            t.Status != TaskStatus.Cancelled)
            .OrderBy(t => t.DueDate)
            .ToList();
    }
    
    public async Task<Dictionary<string, object>> AnalyzeTaskPatternsAsync(Guid? userId = null, CancellationToken cancellationToken = default)
    {
        var tasks = userId.HasValue 
            ? await _repository.GetByAssigneeAsync(userId.Value, cancellationToken)
            : await _repository.GetAllAsync(cancellationToken);
        
        var analysis = new Dictionary<string, object>();
        
        // 任务完成模式分析
        var completedTasks = tasks.Where(t => t.Status == TaskStatus.Completed && t.CompletedAt.HasValue).ToList();
        
        if (completedTasks.Any())
        {
            var completionTimes = completedTasks
                .Where(t => t.StartedAt.HasValue)
                .Select(t => (t.CompletedAt!.Value - t.StartedAt!.Value).TotalHours)
                .ToList();
            
            analysis["平均完成时间"] = completionTimes.Average();
            analysis["最快完成时间"] = completionTimes.Min();
            analysis["最慢完成时间"] = completionTimes.Max();
            analysis["完成时间标准差"] = CalculateStandardDeviation(completionTimes);
        }
        
        // 优先级分布
        analysis["优先级分布"] = tasks.GroupBy(t => t.Priority).ToDictionary(g => g.Key.ToString(), g => g.Count());
        
        // 分类分布
        analysis["分类分布"] = tasks.GroupBy(t => t.Category).ToDictionary(g => g.Key.ToString(), g => g.Count());
        
        // 标签分析
        var allTags = tasks.SelectMany(t => t.Tags).GroupBy(t => t).ToDictionary(g => g.Key, g => g.Count());
        analysis["热门标签"] = allTags.OrderByDescending(kvp => kvp.Value).Take(10).ToDictionary(kvp => kvp.Key, kvp => kvp.Value);
        
        // 工作负载分析
        var workloadByAssignee = tasks
            .Where(t => t.AssigneeId.HasValue)
            .GroupBy(t => t.AssigneeId!.Value)
            .ToDictionary(g => g.Key.ToString(), g => g.Sum(t => t.EstimatedHours));
        analysis["工作负载分布"] = workloadByAssignee;
        
        // 截止日期分析
        var dueDateAnalysis = tasks
            .Where(t => t.DueDate.HasValue)
            .GroupBy(t => new { t.DueDate!.Value.Year, t.DueDate.Value.Month })
            .ToDictionary(g => $"{g.Key.Year}-{g.Key.Month:D2}", g => g.Count());
        analysis["月度截止日期分布"] = dueDateAnalysis;
        
        return analysis;
    }
    
    public async Task<List<TodoItem>> GetTasksByAssigneeAsync(Guid assigneeId, CancellationToken cancellationToken = default)
    {
        return await _repository.GetByAssigneeAsync(assigneeId, cancellationToken);
    }
    
    public async Task<TodoItem> CloneAsync(Guid id, string? newTitle = null, CancellationToken cancellationToken = default)
    {
        var originalTask = await GetByIdAsync(id, cancellationToken);
        if (originalTask == null)
        {
            throw new KeyNotFoundException($"任务 {id} 不存在");
        }
        
        var cloneCommand = new CreateTodoCommand
        {
            Title = newTitle ?? $"克隆 - {originalTask.Title}",
            Description = originalTask.Description,
            Priority = originalTask.Priority,
            Category = originalTask.Category,
            EstimatedHours = originalTask.EstimatedHours,
            Tags = new List<string>(originalTask.Tags),
            // 不复制依赖关系，避免循环依赖
            Dependencies = new List<Guid>(),
            CreatedBy = originalTask.CreatedBy
        };
        
        return await CreateAsync(cloneCommand, cancellationToken);
    }
    
    public async Task<bool> ValidateTaskAsync(TodoItem task, CancellationToken cancellationToken = default)
    {
        // 基本验证
        if (string.IsNullOrWhiteSpace(task.Title))
        {
            return false;
        }
        
        if (task.Title.Length > 200)
        {
            return false;
        }
        
        if (task.EstimatedHours < 0)
        {
            return false;
        }
        
        if (task.Progress < 0 || task.Progress > 100)
        {
            return false;
        }
        
        // 截止日期验证
        if (task.DueDate.HasValue && task.DueDate < task.CreatedAt)
        {
            return false;
        }
        
        // 状态一致性验证
        if (task.Status == TaskStatus.Completed && task.Progress != 100)
        {
            return false;
        }
        
        if (task.Status == TaskStatus.InProgress && task.Progress == 0)
        {
            return false;
        }
        
        return true;
    }
    
    public async Task<List<TodoItem>> GetTasksForReviewAsync(TimeSpan timeframe, CancellationToken cancellationToken = default)
    {
        var cutoffTime = DateTimeOffset.UtcNow.Subtract(timeframe);
        
        var allTasks = await _repository.GetAllAsync(cancellationToken);
        
        return allTasks.Where(t => 
            t.ModifiedAt > cutoffTime && 
            t.Status != TaskStatus.Completed &&
            t.Status != TaskStatus.Cancelled)
            .OrderByDescending(t => t.ModifiedAt)
            .ToList();
    }
    
    public async Task<TodoStatistics> GetTeamStatisticsAsync(List<Guid> userIds, CancellationToken cancellationToken = default)
    {
        var tasks = await _repository.GetByAssigneesAsync(userIds, cancellationToken);
        return await CalculateStatisticsAsync(tasks, cancellationToken);
    }
    
    // 私有辅助方法
    
    private async Task<bool> HasCircularDependencyAsync(Guid taskId, List<Guid> dependencyIds, CancellationToken cancellationToken)
    {
        foreach (var dependencyId in dependencyIds)
        {
            var dependency = await GetByIdAsync(dependencyId, cancellationToken);
            if (dependency == null) continue;
            
            // 检查依赖是否依赖于当前任务
            if (dependency.Dependencies.Contains(taskId))
            {
                return true;
            }
            
            // 递归检查更深层的依赖
            if (await HasCircularDependencyAsync(taskId, dependency.Dependencies, cancellationToken))
            {
                return true;
            }
        }
        
        return false;
    }
    
    private async Task CreateNextRecurringTaskAsync(TodoItem completedTask, CancellationToken cancellationToken)
    {
        // 这里可以实现复杂的重复模式解析逻辑
        // 简化版本：创建下一个相同任务，延后一天
        
        var nextDueDate = completedTask.DueDate?.AddDays(1);
        
        var cloneCommand = new CreateTodoCommand
        {
            Title = completedTask.Title,
            Description = completedTask.Description,
            Priority = completedTask.Priority,
            Category = completedTask.Category,
            DueDate = nextDueDate,
            AssigneeId = completedTask.AssigneeId,
            AssigneeName = completedTask.AssigneeName,
            Tags = new List<string>(completedTask.Tags),
            EstimatedHours = completedTask.EstimatedHours,
            IsRecurring = true,
            RecurrencePattern = completedTask.RecurrencePattern,
            CreatedBy = "system"
        };
        
        await CreateAsync(cloneCommand, cancellationToken);
    }
    
    private async Task ClearTaskCacheAsync(Guid taskId, CancellationToken cancellationToken)
    {
        var cacheKeys = new[]
        {
            $"todo:{taskId}",
            "todo:statistics:global",
            "todo:overdue",
            "todo:due-soon"
        };
        
        foreach (var key in cacheKeys)
        {
            _cache.Remove(key);
        }
    }
    
    private async Task ClearRelatedCacheAsync(TodoItem task, CancellationToken cancellationToken)
    {
        await ClearTaskCacheAsync(task.Id, cancellationToken);
        
        // 如果有分配者，清除分配者相关缓存
        if (task.AssigneeId.HasValue)
        {
            _cache.Remove($"todos:assignee:{task.AssigneeId}");
        }
    }
    
    private void CleanupCache(object? state)
    {
        try
        {
            // 这里可以添加更复杂的缓存清理逻辑
            _logger.LogDebug("执行缓存清理");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "缓存清理失败");
        }
    }
    
    private static double CalculateStandardDeviation(List<double> values)
    {
        if (values.Count < 2) return 0;
        
        var average = values.Average();
        var squaredDifferences = values.Select(value => Math.Pow(value - average, 2));
        var variance = squaredDifferences.Average();
        return Math.Sqrt(variance);
    }
    
    private async Task<TodoStatistics> CalculateStatisticsAsync(List<TodoItem> tasks, CancellationToken cancellationToken)
    {
        var stats = new TodoStatistics
        {
            TotalTasks = tasks.Count,
            CompletedTasks = tasks.Count(t => t.Status == TaskStatus.Completed),
            InProgressTasks = tasks.Count(t => t.Status == TaskStatus.InProgress),
            PendingTasks = tasks.Count(t => t.Status == TaskStatus.Pending),
            TasksByPriority = tasks.GroupBy(t => t.Priority).ToDictionary(g => g.Key, g => g.Count()),
            TasksByStatus = tasks.GroupBy(t => t.Status).ToDictionary(g => g.Key, g => g.Count()),
            TasksByCategory = tasks.GroupBy(t => t.Category).ToDictionary(g => g.Key, g => g.Count()),
            LastUpdated = DateTime.UtcNow
        };
        
        stats.CompletionRate = stats.TotalTasks > 0 ? (double)stats.CompletedTasks / stats.TotalTasks * 100 : 0;
        
        return stats;
    }
    
    public void Dispose()
    {
        _cleanupTimer?.Dispose();
        _semaphore?.Dispose();
    }
}

/// <summary>
/// 事件总线接口
/// </summary>
public interface IEventBus
{
    Task PublishAsync<T>(T eventData, CancellationToken cancellationToken = default) where T : class;
}

/// <summary>
/// 任务创建事件
/// </summary>
public class TodoCreatedEvent
{
    public TodoItem Task { get; }
    
    public TodoCreatedEvent(TodoItem task)
    {
        Task = task;
    }
}

/// <summary>
/// 任务更新事件
/// </summary>
public class TodoUpdatedEvent
{
    public TodoItem Task { get; }
    
    public TodoUpdatedEvent(TodoItem task)
    {
        Task = task;
    }
}

/// <summary>
/// 任务删除事件
/// </summary>
public class TodoDeletedEvent
{
    public TodoItem Task { get; }
    
    public TodoDeletedEvent(TodoItem task)
    {
        Task = task;
    }
}

/// <summary>
/// 任务状态变更事件
/// </summary>
public class TodoStatusChangedEvent
{
    public TodoItem Task { get; }
    public TaskStatus OldStatus { get; }
    
    public TodoStatusChangedEvent(TodoItem task, TaskStatus oldStatus)
    {
        Task = task;
        OldStatus = oldStatus;
    }
}

/// <summary>
/// 任务优先级变更事件
/// </summary>
public class TodoPriorityChangedEvent
{
    public TodoItem Task { get; }
    public Priority OldPriority { get; }
    
    public TodoPriorityChangedEvent(TodoItem task, Priority oldPriority)
    {
        Task = task;
        OldPriority = oldPriority;
    }
}

/// <summary>
/// 任务依赖添加事件
/// </summary>
public class TodoDependencyAddedEvent
{
    public TodoItem Task { get; }
    public TodoItem Dependency { get; }
    
    public TodoDependencyAddedEvent(TodoItem task, TodoItem dependency)
    {
        Task = task;
        Dependency = dependency;
    }
}

/// <summary>
/// 任务依赖移除事件
/// </summary>
public class TodoDependencyRemovedEvent
{
    public TodoItem Task { get; }
    public Guid RemovedDependencyId { get; }
    
    public TodoDependencyRemovedEvent(TodoItem task, Guid removedDependencyId)
    {
        Task = task;
        RemovedDependencyId = removedDependencyId;
    }
}

// 程序入口点
var builder = WebApplication.CreateBuilder(args);

// 配置服务
builder.Services.AddMemoryCache();
builder.Services.AddScoped<ITodoRepository, TodoRepository>();
builder.Services.AddScoped<IPriorityCalculator, PriorityCalculator>();
builder.Services.AddScoped<ITodoService, TodoService>();
builder.Services.AddScoped<IEventBus, EventBus>();

// 添加Scrutor自动注册
builder.Services.Scan(scan => scan
    .FromAssemblies(Assembly.GetExecutingAssembly())
    .AddClasses(classes => classes.AssignableTo<ITodoService>())
    .AsImplementedInterfaces()
    .WithScopedLifetime());

// 配置应用
var app = builder.Build();

// 配置中间件
if (app.Environment.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
}

app.UseRouting();
app.UseEndpoints(endpoints =>
{
    endpoints.MapGet("/", () => "Todo Management System is running!");
    
    // 健康检查端点
    endpoints.MapGet("/health", () => Results.Ok(new { Status = "Healthy", Timestamp = DateTime.UtcNow }));
});

Console.WriteLine("Todo Management System started successfully!");
Console.WriteLine($"Environment: {app.Environment.EnvironmentName}");
Console.WriteLine("Press Ctrl+C to shutdown");

app.Run();