#!/usr/bin/env dotnet
// <auto-generated/>
// ------------------------------------------------------------------------------
// <auto-generated by VSA Architecture Team>
// 生成时间: 2024-12-01
// 描述: 智能任务管理系统 - 数据访问层实现
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Logging;
using System.Text.Json;
using System.ComponentModel;
using System.Reflection;
using System.Collections.Concurrent;
using System.Diagnostics;
using System.IO;
using System.Text;
using Microsoft.Extensions.Options;

namespace VSA.TodoSystem.Infrastructure;

/// <summary>
/// 任务仓储接口
/// </summary>
public interface ITodoRepository
{
    Task<TodoItem> CreateAsync(TodoItem task, CancellationToken cancellationToken = default);
    
    Task<TodoItem?> GetByIdAsync(Guid id, CancellationToken cancellationToken = default);
    
    Task<List<TodoItem>> GetByIdsAsync(List<Guid> ids, CancellationToken cancellationToken = default);
    
    Task<List<TodoItem>> GetAllAsync(CancellationToken cancellationToken = default);
    
    Task<TodoItem> UpdateAsync(TodoItem task, CancellationToken cancellationToken = default);
    
    Task<bool> DeleteAsync(Guid id, CancellationToken cancellationToken = default);
    
    Task<List<TodoItem>> GetPagedAsync(TodoQuery query, CancellationToken cancellationToken = default);
    
    Task<List<TodoItem>> GetByAssigneeAsync(Guid assigneeId, CancellationToken cancellationToken = default);
    
    Task<List<TodoItem>> GetByAssigneesAsync(List<Guid> assigneeIds, CancellationToken cancellationToken = default);
    
    Task<List<TodoItem>> GetDependentsAsync(Guid taskId, CancellationToken cancellationToken = default);
    
    Task<List<TodoItem>> GetOverdueAsync(CancellationToken cancellationToken = default);
    
    Task<List<TodoItem>> GetByStatusAsync(TaskStatus status, CancellationToken cancellationToken = default);
    
    Task<List<TodoItem>> GetByPriorityAsync(Priority priority, CancellationToken cancellationToken = default);
    
    Task<List<TodoItem>> GetByCategoryAsync(TaskCategory category, CancellationToken cancellationToken = default);
    
    Task<List<TodoItem>> SearchAsync(string searchText, CancellationToken cancellationToken = default);
    
    Task<List<TodoItem>> GetByTagsAsync(List<string> tags, CancellationToken cancellationToken = default);
    
    Task<List<TodoItem>> GetDueBeforeAsync(DateTimeOffset dateTime, CancellationToken cancellationToken = default);
    
    Task<List<TodoItem>> GetDueAfterAsync(DateTimeOffset dateTime, CancellationToken cancellationToken = default);
    
    Task<List<TodoItem>> GetCreatedAfterAsync(DateTimeOffset dateTime, CancellationToken cancellationToken = default);
    
    Task<List<TodoItem>> GetModifiedAfterAsync(DateTimeOffset dateTime, CancellationToken cancellationToken = default);
    
    Task<List<TodoItem>> GetWithDependenciesAsync(Guid taskId, CancellationToken cancellationToken = default);
    
    Task<List<TodoItem>> GetDependenciesAsync(Guid taskId, CancellationToken cancellationToken = default);
    
    Task<Dictionary<TaskStatus, int>> GetStatusStatisticsAsync(CancellationToken cancellationToken = default);
    
    Task<Dictionary<Priority, int>> GetPriorityStatisticsAsync(CancellationToken cancellationToken = default);
    
    Task<Dictionary<TaskCategory, int>> GetCategoryStatisticsAsync(CancellationToken cancellationToken = default);
    
    Task<Dictionary<string, int>> GetTagStatisticsAsync(CancellationToken cancellationToken = default);
    
    Task<Dictionary<string, int>> GetAssigneeStatisticsAsync(CancellationToken cancellationToken = default);
    
    Task<List<TodoItem>> GetRecurringTasksAsync(CancellationToken cancellationToken = default);
    
    Task<List<TodoItem>> GetBlockedTasksAsync(CancellationToken cancellationToken = default);
    
    Task<bool> ExistsAsync(Guid id, CancellationToken cancellationToken = default);
    
    Task<int> CountAsync(CancellationToken cancellationToken = default);
    
    Task<int> CountByStatusAsync(TaskStatus status, CancellationToken cancellationToken = default);
    
    Task<int> CountByPriorityAsync(Priority priority, CancellationToken cancellationToken = default);
    
    Task<List<TodoItem>> GetTasksWithPendingDependenciesAsync(CancellationToken cancellationToken = default);
    
    Task<List<TodoItem>> GetTasksByDateRangeAsync(DateTimeOffset startDate, DateTimeOffset endDate, CancellationToken cancellationToken = default);
}

/// <summary>
/// 简单文件存储实现
/// </summary>
[System.ComponentModel.Description("文件存储任务仓储")]
public class TodoRepository : ITodoRepository
{
    private readonly ILogger<TodoRepository> _logger;
    private readonly IMemoryCache _cache;
    private readonly string _storagePath;
    private readonly SemaphoreSlim _fileLock = new(1, 1);
    private readonly Timer _cacheCleanupTimer;
    
    private readonly string _tasksFilePath;
    private readonly string _indexFilePath;
    private readonly ConcurrentDictionary<Guid, DateTimeOffset> _lastModified = new();
    
    public TodoRepository(
        ILogger<TodoRepository> logger,
        IMemoryCache cache)
    {
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        _cache = cache ?? throw new ArgumentNullException(nameof(cache));
        
        // 设置存储路径
        _storagePath = Path.Combine(Directory.GetCurrentDirectory(), "data", "todos");
        _tasksFilePath = Path.Combine(_storagePath, "tasks.json");
        _indexFilePath = Path.Combine(_storagePath, "index.json");
        
        // 确保目录存在
        Directory.CreateDirectory(_storagePath);
        
        // 初始化存储文件
        InitializeStorage();
        
        // 定时清理缓存
        _cacheCleanupTimer = new Timer(CleanupCache, null, TimeSpan.FromMinutes(5), TimeSpan.FromMinutes(5));
    }
    
    public async Task<TodoItem> CreateAsync(TodoItem task, CancellationToken cancellationToken = default)
    {
        await _fileLock.WaitAsync(cancellationToken);
        try
        {
            var tasks = await LoadTasksAsync(cancellationToken);
            
            // 检查ID是否已存在
            if (tasks.Any(t => t.Id == task.Id))
            {
                throw new InvalidOperationException($"任务 ID {task.Id} 已存在");
            }
            
            tasks.Add(task);
            await SaveTasksAsync(tasks, cancellationToken);
            
            // 更新缓存
            _cache.Set($"todo:{task.Id}", task, TimeSpan.FromMinutes(30));
            _lastModified[task.Id] = DateTimeOffset.UtcNow;
            
            _logger.LogInformation("任务创建成功: {TaskId}, 标题: {Title}", task.Id, task.Title);
            
            return task;
        }
        finally
        {
            _fileLock.Release();
        }
    }
    
    public async Task<TodoItem?> GetByIdAsync(Guid id, CancellationToken cancellationToken = default)
    {
        var cacheKey = $"todo:{id}";
        
        if (_cache.TryGetValue(cacheKey, out TodoItem? cachedTask))
        {
            return cachedTask;
        }
        
        await _fileLock.WaitAsync(cancellationToken);
        try
        {
            var tasks = await LoadTasksAsync(cancellationToken);
            var task = tasks.FirstOrDefault(t => t.Id == id);
            
            if (task != null)
            {
                _cache.Set(cacheKey, task, TimeSpan.FromMinutes(30));
            }
            
            return task;
        }
        finally
        {
            _fileLock.Release();
        }
    }
    
    public async Task<List<TodoItem>> GetByIdsAsync(List<Guid> ids, CancellationToken cancellationToken = default)
    {
        var result = new List<TodoItem>();
        
        await _fileLock.WaitAsync(cancellationToken);
        try
        {
            var tasks = await LoadTasksAsync(cancellationToken);
            
            foreach (var id in ids)
            {
                var cacheKey = $"todo:{id}";
                if (_cache.TryGetValue(cacheKey, out TodoItem? cachedTask))
                {
                    result.Add(cachedTask);
                    continue;
                }
                
                var task = tasks.FirstOrDefault(t => t.Id == id);
                if (task != null)
                {
                    result.Add(task);
                    _cache.Set(cacheKey, task, TimeSpan.FromMinutes(30));
                }
            }
        }
        finally
        {
            _fileLock.Release();
        }
        
        return result;
    }
    
    public async Task<List<TodoItem>> GetAllAsync(CancellationToken cancellationToken = default)
    {
        var cacheKey = "todos:all";
        
        if (_cache.TryGetValue(cacheKey, out List<TodoItem>? cachedTasks))
        {
            return cachedTasks;
        }
        
        await _fileLock.WaitAsync(cancellationToken);
        try
        {
            var tasks = await LoadTasksAsync(cancellationToken);
            
            _cache.Set(cacheKey, tasks, TimeSpan.FromMinutes(15));
            
            return tasks;
        }
        finally
        {
            _fileLock.Release();
        }
    }
    
    public async Task<TodoItem> UpdateAsync(TodoItem task, CancellationToken cancellationToken = default)
    {
        await _fileLock.WaitAsync(cancellationToken);
        try
        {
            var tasks = await LoadTasksAsync(cancellationToken);
            var existingIndex = tasks.FindIndex(t => t.Id == task.Id);
            
            if (existingIndex == -1)
            {
                throw new KeyNotFoundException($"任务 {task.Id} 不存在");
            }
            
            tasks[existingIndex] = task;
            await SaveTasksAsync(tasks, cancellationToken);
            
            // 更新缓存
            _cache.Set($"todo:{task.Id}", task, TimeSpan.FromMinutes(30));
            _cache.Remove("todos:all"); // 清除全量缓存
            
            _lastModified[task.Id] = DateTimeOffset.UtcNow;
            
            _logger.LogInformation("任务更新成功: {TaskId}, 标题: {Title}", task.Id, task.Title);
            
            return task;
        }
        finally
        {
            _fileLock.Release();
        }
    }
    
    public async Task<bool> DeleteAsync(Guid id, CancellationToken cancellationToken = default)
    {
        await _fileLock.WaitAsync(cancellationToken);
        try
        {
            var tasks = await LoadTasksAsync(cancellationToken);
            var task = tasks.FirstOrDefault(t => t.Id == id);
            
            if (task == null)
            {
                return false;
            }
            
            tasks.Remove(task);
            await SaveTasksAsync(tasks, cancellationToken);
            
            // 清除缓存
            _cache.Remove($"todo:{id}");
            _cache.Remove("todos:all");
            _lastModified.TryRemove(id, out _);
            
            _logger.LogInformation("任务删除成功: {TaskId}", id);
            
            return true;
        }
        finally
        {
            _fileLock.Release();
        }
    }
    
    public async Task<List<TodoItem>> GetPagedAsync(TodoQuery query, CancellationToken cancellationToken = default)
    {
        var allTasks = await GetAllAsync(cancellationToken);
        
        // 应用过滤条件
        var filteredTasks = FilterTasks(allTasks, query);
        
        // 应用排序
        var sortedTasks = SortTasks(filteredTasks, query);
        
        // 应用分页
        var totalCount = sortedTasks.Count;
        var pagedTasks = sortedTasks
            .Skip((query.PageNumber - 1) * query.PageSize)
            .Take(query.PageSize)
            .ToList();
        
        return pagedTasks;
    }
    
    public async Task<List<TodoItem>> GetByAssigneeAsync(Guid assigneeId, CancellationToken cancellationToken = default)
    {
        var cacheKey = $"todos:assignee:{assigneeId}";
        
        if (_cache.TryGetValue(cacheKey, out List<TodoItem>? cachedTasks))
        {
            return cachedTasks;
        }
        
        var allTasks = await GetAllAsync(cancellationToken);
        var tasks = allTasks.Where(t => t.AssigneeId == assigneeId).ToList();
        
        _cache.Set(cacheKey, tasks, TimeSpan.FromMinutes(15));
        
        return tasks;
    }
    
    public async Task<List<TodoItem>> GetByAssigneesAsync(List<Guid> assigneeIds, CancellationToken cancellationToken = default)
    {
        var allTasks = await GetAllAsync(cancellationToken);
        
        return allTasks.Where(t => t.AssigneeId.HasValue && assigneeIds.Contains(t.AssigneeId.Value)).ToList();
    }
    
    public async Task<List<TodoItem>> GetDependentsAsync(Guid taskId, CancellationToken cancellationToken = default)
    {
        var allTasks = await GetAllAsync(cancellationToken);
        
        return allTasks.Where(t => t.Dependencies.Contains(taskId)).ToList();
    }
    
    public async Task<List<TodoItem>> GetOverdueAsync(CancellationToken cancellationToken = default)
    {
        var cacheKey = "todos:overdue";
        
        if (_cache.TryGetValue(cacheKey, out List<TodoItem>? cachedTasks))
        {
            return cachedTasks;
        }
        
        var allTasks = await GetAllAsync(cancellationToken);
        var now = DateTimeOffset.UtcNow;
        
        var overdueTasks = allTasks.Where(t => 
            t.DueDate.HasValue && 
            t.DueDate < now && 
            t.Status != TaskStatus.Completed &&
            t.Status != TaskStatus.Cancelled).ToList();
        
        _cache.Set(cacheKey, overdueTasks, TimeSpan.FromMinutes(5));
        
        return overdueTasks;
    }
    
    public async Task<List<TodoItem>> GetByStatusAsync(TaskStatus status, CancellationToken cancellationToken = default)
    {
        var allTasks = await GetAllAsync(cancellationToken);
        
        return allTasks.Where(t => t.Status == status).ToList();
    }
    
    public async Task<List<TodoItem>> GetByPriorityAsync(Priority priority, CancellationToken cancellationToken = default)
    {
        var allTasks = await GetAllAsync(cancellationToken);
        
        return allTasks.Where(t => t.Priority == priority).ToList();
    }
    
    public async Task<List<TodoItem>> GetByCategoryAsync(TaskCategory category, CancellationToken cancellationToken = default)
    {
        var allTasks = await GetAllAsync(cancellationToken);
        
        return allTasks.Where(t => t.Category == category).ToList();
    }
    
    public async Task<List<TodoItem>> SearchAsync(string searchText, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(searchText))
        {
            return await GetAllAsync(cancellationToken);
        }
        
        var allTasks = await GetAllAsync(cancellationToken);
        var lowerSearchText = searchText.ToLower();
        
        return allTasks.Where(t => 
            t.Title.ToLower().Contains(lowerSearchText) ||
            (t.Description != null && t.Description.ToLower().Contains(lowerSearchText)) ||
            t.Tags.Any(tag => tag.ToLower().Contains(lowerSearchText)) ||
            (t.AssigneeName != null && t.AssigneeName.ToLower().Contains(lowerSearchText))).ToList();
    }
    
    public async Task<List<TodoItem>> GetByTagsAsync(List<string> tags, CancellationToken cancellationToken = default)
    {
        var allTasks = await GetAllAsync(cancellationToken);
        
        return allTasks.Where(t => tags.Any(tag => t.Tags.Contains(tag, StringComparer.OrdinalIgnoreCase))).ToList();
    }
    
    public async Task<List<TodoItem>> GetDueBeforeAsync(DateTimeOffset dateTime, CancellationToken cancellationToken = default)
    {
        var allTasks = await GetAllAsync(cancellationToken);
        
        return allTasks.Where(t => t.DueDate.HasValue && t.DueDate <= dateTime).ToList();
    }
    
    public async Task<List<TodoItem>> GetDueAfterAsync(DateTimeOffset dateTime, CancellationToken cancellationToken = default)
    {
        var allTasks = await GetAllAsync(cancellationToken);
        
        return allTasks.Where(t => t.DueDate.HasValue && t.DueDate >= dateTime).ToList();
    }
    
    public async Task<List<TodoItem>> GetCreatedAfterAsync(DateTimeOffset dateTime, CancellationToken cancellationToken = default)
    {
        var allTasks = await GetAllAsync(cancellationToken);
        
        return allTasks.Where(t => t.CreatedAt >= dateTime).ToList();
    }
    
    public async Task<List<TodoItem>> GetModifiedAfterAsync(DateTimeOffset dateTime, CancellationToken cancellationToken = default)
    {
        var allTasks = await GetAllAsync(cancellationToken);
        
        return allTasks.Where(t => t.ModifiedAt.HasValue && t.ModifiedAt >= dateTime).ToList();
    }
    
    public async Task<List<TodoItem>> GetWithDependenciesAsync(Guid taskId, CancellationToken cancellationToken = default)
    {
        var task = await GetByIdAsync(taskId, cancellationToken);
        if (task == null)
        {
            return new List<TodoItem>();
        }
        
        var dependencies = await GetByIdsAsync(task.Dependencies, cancellationToken);
        var dependents = await GetDependentsAsync(taskId, cancellationToken);
        
        var result = new List<TodoItem> { task };
        result.AddRange(dependencies);
        result.AddRange(dependents);
        
        return result.Distinct().ToList();
    }
    
    public async Task<List<TodoItem>> GetDependenciesAsync(Guid taskId, CancellationToken cancellationToken = default)
    {
        var task = await GetByIdAsync(taskId, cancellationToken);
        if (task?.Dependencies == null || !task.Dependencies.Any())
        {
            return new List<TodoItem>();
        }
        
        return await GetByIdsAsync(task.Dependencies, cancellationToken);
    }
    
    public async Task<Dictionary<TaskStatus, int>> GetStatusStatisticsAsync(CancellationToken cancellationToken = default)
    {
        var allTasks = await GetAllAsync(cancellationToken);
        
        return allTasks.GroupBy(t => t.Status).ToDictionary(g => g.Key, g => g.Count());
    }
    
    public async Task<Dictionary<Priority, int>> GetPriorityStatisticsAsync(CancellationToken cancellationToken = default)
    {
        var allTasks = await GetAllAsync(cancellationToken);
        
        return allTasks.GroupBy(t => t.Priority).ToDictionary(g => g.Key, g => g.Count());
    }
    
    public async Task<Dictionary<TaskCategory, int>> GetCategoryStatisticsAsync(CancellationToken cancellationToken = default)
    {
        var allTasks = await GetAllAsync(cancellationToken);
        
        return allTasks.GroupBy(t => t.Category).ToDictionary(g => g.Key, g => g.Count());
    }
    
    public async Task<Dictionary<string, int>> GetTagStatisticsAsync(CancellationToken cancellationToken = default)
    {
        var allTasks = await GetAllAsync(cancellationToken);
        var tagStats = new Dictionary<string, int>();
        
        foreach (var task in allTasks)
        {
            foreach (var tag in task.Tags)
            {
                tagStats[tag] = tagStats.GetValueOrDefault(tag, 0) + 1;
            }
        }
        
        return tagStats.OrderByDescending(kvp => kvp.Value).ToDictionary(kvp => kvp.Key, kvp => kvp.Value);
    }
    
    public async Task<Dictionary<string, int>> GetAssigneeStatisticsAsync(CancellationToken cancellationToken = default)
    {
        var allTasks = await GetAllAsync(cancellationToken);
        var assigneeStats = new Dictionary<string, int>();
        
        foreach (var task in allTasks.Where(t => !string.IsNullOrEmpty(t.AssigneeName)))
        {
            var assigneeName = task.AssigneeName!;
            assigneeStats[assigneeName] = assigneeStats.GetValueOrDefault(assigneeName, 0) + 1;
        }
        
        return assigneeStats.OrderByDescending(kvp => kvp.Value).ToDictionary(kvp => kvp.Key, kvp => kvp.Value);
    }
    
    public async Task<List<TodoItem>> GetRecurringTasksAsync(CancellationToken cancellationToken = default)
    {
        var allTasks = await GetAllAsync(cancellationToken);
        
        return allTasks.Where(t => t.IsRecurring).ToList();
    }
    
    public async Task<List<TodoItem>> GetBlockedTasksAsync(CancellationToken cancellationToken = default)
    {
        var allTasks = await GetAllAsync(cancellationToken);
        
        return allTasks.Where(t => t.Status == TaskStatus.Blocked).ToList();
    }
    
    public async Task<bool> ExistsAsync(Guid id, CancellationToken cancellationToken = default)
    {
        var task = await GetByIdAsync(id, cancellationToken);
        return task != null;
    }
    
    public async Task<int> CountAsync(CancellationToken cancellationToken = default)
    {
        var allTasks = await GetAllAsync(cancellationToken);
        return allTasks.Count;
    }
    
    public async Task<int> CountByStatusAsync(TaskStatus status, CancellationToken cancellationToken = default)
    {
        var allTasks = await GetAllAsync(cancellationToken);
        return allTasks.Count(t => t.Status == status);
    }
    
    public async Task<int> CountByPriorityAsync(Priority priority, CancellationToken cancellationToken = default)
    {
        var allTasks = await GetAllAsync(cancellationToken);
        return allTasks.Count(t => t.Priority == priority);
    }
    
    public async Task<List<TodoItem>> GetTasksWithPendingDependenciesAsync(CancellationToken cancellationToken = default)
    {
        var allTasks = await GetAllAsync(cancellationToken);
        var tasksWithPendingDeps = new List<TodoItem>();
        
        foreach (var task in allTasks.Where(t => t.Dependencies.Any()))
        {
            var dependencies = await GetByIdsAsync(task.Dependencies, cancellationToken);
            var pendingDependencies = dependencies.Where(d => d.Status != TaskStatus.Completed).ToList();
            
            if (pendingDependencies.Any())
            {
                tasksWithPendingDeps.Add(task);
            }
        }
        
        return tasksWithPendingDeps;
    }
    
    public async Task<List<TodoItem>> GetTasksByDateRangeAsync(DateTimeOffset startDate, DateTimeOffset endDate, CancellationToken cancellationToken = default)
    {
        var allTasks = await GetAllAsync(cancellationToken);
        
        return allTasks.Where(t => 
            t.CreatedAt >= startDate && 
            t.CreatedAt <= endDate).ToList();
    }
    
    // 私有辅助方法
    
    private void InitializeStorage()
    {
        try
        {
            // 创建任务文件
            if (!File.Exists(_tasksFilePath))
            {
                File.WriteAllText(_tasksFilePath, "[]");
            }
            
            // 创建索引文件
            if (!File.Exists(_indexFilePath))
            {
                File.WriteAllText(_indexFilePath, "{}");
            }
            
            _logger.LogInformation("存储初始化完成: {StoragePath}", _storagePath);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "存储初始化失败");
            throw;
        }
    }
    
    private async Task<List<TodoItem>> LoadTasksAsync(CancellationToken cancellationToken = default)
    {
        try
        {
            var jsonContent = await File.ReadAllTextAsync(_tasksFilePath, cancellationToken);
            
            if (string.IsNullOrWhiteSpace(jsonContent))
            {
                return new List<TodoItem>();
            }
            
            var options = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true,
                Converters = { new JsonStringEnumConverter() }
            };
            
            var tasks = JsonSerializer.Deserialize<List<TodoItem>>(jsonContent, options) ?? new List<TodoItem>();
            
            return tasks;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "加载任务数据失败");
            return new List<TodoItem>();
        }
    }
    
    private async Task SaveTasksAsync(List<TodoItem> tasks, CancellationToken cancellationToken = default)
    {
        try
        {
            var options = new JsonSerializerOptions
            {
                WriteIndented = true,
                Converters = { new JsonStringEnumConverter() }
            };
            
            var jsonContent = JsonSerializer.Serialize(tasks, options);
            await File.WriteAllTextAsync(_tasksFilePath, jsonContent, cancellationToken);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "保存任务数据失败");
            throw;
        }
    }
    
    private List<TodoItem> FilterTasks(List<TodoItem> tasks, TodoQuery query)
    {
        var filtered = tasks.AsEnumerable();
        
        if (query.Status.HasValue)
        {
            filtered = filtered.Where(t => t.Status == query.Status.Value);
        }
        
        if (query.Priority.HasValue)
        {
            filtered = filtered.Where(t => t.Priority == query.Priority.Value);
        }
        
        if (query.Category.HasValue)
        {
            filtered = filtered.Where(t => t.Category == query.Category.Value);
        }
        
        if (query.AssigneeId.HasValue)
        {
            filtered = filtered.Where(t => t.AssigneeId == query.AssigneeId.Value);
        }
        
        if (query.DueDateFrom.HasValue)
        {
            filtered = filtered.Where(t => t.DueDate >= query.DueDateFrom.Value);
        }
        
        if (query.DueDateTo.HasValue)
        {
            filtered = filtered.Where(t => t.DueDate <= query.DueDateTo.Value);
        }
        
        if (!string.IsNullOrWhiteSpace(query.SearchText))
        {
            var searchText = query.SearchText.ToLower();
            filtered = filtered.Where(t => 
                t.Title.ToLower().Contains(searchText) ||
                (t.Description != null && t.Description.ToLower().Contains(searchText)) ||
                t.Tags.Any(tag => tag.ToLower().Contains(searchText)));
        }
        
        if (query.Tags?.Any() == true)
        {
            filtered = filtered.Where(t => 
                query.Tags.Any(queryTag => 
                    t.Tags.Contains(queryTag, StringComparer.OrdinalIgnoreCase)));
        }
        
        return filtered.ToList();
    }
    
    private List<TodoItem> SortTasks(List<TodoItem> tasks, TodoQuery query)
    {
        var sorted = tasks.AsEnumerable();
        
        if (!string.IsNullOrWhiteSpace(query.SortBy))
        {
            sorted = query.SortBy.ToLower() switch
            {
                "title" => query.SortDescending ? sorted.OrderByDescending(t => t.Title) : sorted.OrderBy(t => t.Title),
                "priority" => query.SortDescending ? sorted.OrderByDescending(t => t.Priority) : sorted.OrderBy(t => t.Priority),
                "status" => query.SortDescending ? sorted.OrderByDescending(t => t.Status) : sorted.OrderBy(t => t.Status),
                "category" => query.SortDescending ? sorted.OrderByDescending(t => t.Category) : sorted.OrderBy(t => t.Category),
                "createdat" => query.SortDescending ? sorted.OrderByDescending(t => t.CreatedAt) : sorted.OrderBy(t => t.CreatedAt),
                "modifiedat" => query.SortDescending ? sorted.OrderByDescending(t => t.ModifiedAt) : sorted.OrderBy(t => t.ModifiedAt),
                "duedate" => query.SortDescending ? sorted.OrderByDescending(t => t.DueDate) : sorted.OrderBy(t => t.DueDate),
                "estimatedhours" => query.SortDescending ? sorted.OrderByDescending(t => t.EstimatedHours) : sorted.OrderBy(t => t.EstimatedHours),
                "progress" => query.SortDescending ? sorted.OrderByDescending(t => t.Progress) : sorted.OrderBy(t => t.Progress),
                _ => query.SortDescending ? sorted.OrderByDescending(t => t.CreatedAt) : sorted.OrderBy(t => t.CreatedAt)
            };
        }
        else
        {
            // 默认排序：按创建时间倒序
            sorted = sorted.OrderByDescending(t => t.CreatedAt);
        }
        
        return sorted.ToList();
    }
    
    private void CleanupCache(object? state)
    {
        try
        {
            // 清理过期的任务缓存
            var cacheKeys = _cache.GetKeys<string>();
            var taskKeys = cacheKeys.Where(key => key.StartsWith("todo:")).ToList();
            
            foreach (var key in taskKeys)
            {
                // 检查任务是否已被删除
                if (key.StartsWith("todo:") && key != "todo:all")
                {
                    var taskId = key.Substring(5);
                    if (Guid.TryParse(taskId, out var id))
                    {
                        if (_lastModified.TryGetValue(id, out var lastModified))
                        {
                            // 如果任务超过1小时未修改，清除缓存
                            if (DateTimeOffset.UtcNow - lastModified > TimeSpan.FromHours(1))
                            {
                                _cache.Remove(key);
                            }
                        }
                    }
                }
            }
            
            _logger.LogDebug("缓存清理完成，清理了 {Count} 个键", taskKeys.Count);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "缓存清理失败");
        }
    }
    
    public void Dispose()
    {
        _cacheCleanupTimer?.Dispose();
        _fileLock?.Dispose();
    }
}

/// <summary>
/// 事件总线实现
/// </summary>
public class EventBus : IEventBus
{
    private readonly ILogger<EventBus> _logger;
    private readonly Dictionary<Type, List<Func<object, CancellationToken, Task>>> _handlers;
    
    public EventBus(ILogger<EventBus> logger)
    {
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        _handlers = new Dictionary<Type, List<Func<object, CancellationToken, Task>>>();
    }
    
    public async Task PublishAsync<T>(T eventData, CancellationToken cancellationToken = default) where T : class
    {
        var eventType = typeof(T);
        
        if (_handlers.TryGetValue(eventType, out var handlers))
        {
            var tasks = handlers.Select(handler => 
            {
                try
                {
                    return handler(eventData, cancellationToken);
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, "事件处理器执行失败: {EventType}", eventType.Name);
                    return Task.CompletedTask;
                }
            });
            
            await Task.WhenAll(tasks);
        }
        
        _logger.LogDebug("事件发布完成: {EventType}", eventType.Name);
    }
    
    public void Subscribe<T>(Func<T, CancellationToken, Task> handler) where T : class
    {
        var eventType = typeof(T);
        
        if (!_handlers.ContainsKey(eventType))
        {
            _handlers[eventType] = new List<Func<object, CancellationToken, Task>>();
        }
        
        _handlers[eventType].Add((data, ct) => handler((T)data, ct));
    }
}

// 程序入口点
var builder = WebApplication.CreateBuilder(args);

// 配置服务
builder.Services.AddMemoryCache();
builder.Services.AddScoped<ITodoRepository, TodoRepository>();
builder.Services.AddScoped<IEventBus, EventBus>();

// 添加Scrutor自动注册
builder.Services.Scan(scan => scan
    .FromAssemblies(Assembly.GetExecutingAssembly())
    .AddClasses(classes => classes.AssignableTo<ITodoRepository>())
    .AsImplementedInterfaces()
    .WithScopedLifetime());

// 配置应用
var app = builder.Build();

// 配置中间件
if (app.Environment.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
}

app.UseRouting();
app.UseEndpoints(endpoints =>
{
    endpoints.MapGet("/", () => "Todo Repository is running!");
    
    // 健康检查端点
    endpoints.MapGet("/health", () => Results.Ok(new { Status = "Healthy", Timestamp = DateTime.UtcNow }));
    
    // 获取所有任务端点
    endpoints.MapGet("/tasks", async (ITodoRepository repository) =>
    {
        var tasks = await repository.GetAllAsync();
        return Results.Ok(tasks);
    });
    
    // 根据ID获取任务端点
    endpoints.MapGet("/tasks/{id:guid}", async (Guid id, ITodoRepository repository) =>
    {
        var task = await repository.GetByIdAsync(id);
        return task != null ? Results.Ok(task) : Results.NotFound();
    });
});

Console.WriteLine("Todo Repository started successfully!");
Console.WriteLine($"Storage Path: {Path.Combine(Directory.GetCurrentDirectory(), "data", "todos")}");
Console.WriteLine("Press Ctrl+C to shutdown");

app.Run();