<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net11.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
		<Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
		<OutputType>Library</OutputType>
		<AppDesignerFolder>Properties</AppDesignerFolder>
		<RootNamespace>Goroutine</RootNamespace>
		<AssemblyName>Goroutine</AssemblyName>
		<FileAlignment>512</FileAlignment>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<DebugSymbols>true</DebugSymbols>
		<DebugType>full</DebugType>
		<Optimize>false</Optimize>
		<OutputPath>bin\Debug\</OutputPath>
		<DefineConstants>TRACE;DEBUG</DefineConstants>
		<ErrorReport>prompt</ErrorReport>
		<WarningLevel>4</WarningLevel>
		<WarningsAsErrors>CS4014</WarningsAsErrors>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
		<DebugType>pdbonly</DebugType>
		<Optimize>true</Optimize>
		<OutputPath>bin\Release\</OutputPath>
		<DefineConstants>TRACE</DefineConstants>
		<ErrorReport>prompt</ErrorReport>
		<WarningLevel>4</WarningLevel>
		<WarningsAsErrors>CS4014</WarningsAsErrors>
	</PropertyGroup>
	<PropertyGroup>
		<StartupObject />
	</PropertyGroup>
	<ItemGroup>
	  <Compile Remove="Go\**" />
	  <EmbeddedResource Remove="Go\**" />
	  <None Remove="Go\**" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="System" />
		<Reference Include="System.Core" />
		<Reference Include="System.Windows.Forms" />
		<Reference Include="System.Xml.Linq" />
		<Reference Include="System.Data.DataSetExtensions" />
		<Reference Include="Microsoft.CSharp" />
		<Reference Include="System.Data" />
		<Reference Include="System.Net.Http" />
		<Reference Include="System.Xml" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="LanguageExt.Core" Version="4.4.9" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
		<PackageReference Include="Nito.AsyncEx" Version="5.1.2" />
		<PackageReference Include="System.IO.Ports" Version="10.0.5" />
	</ItemGroup>

</Project>
